# Generated by Django 4.2.7 on 2026-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airportpickup",
            name="service_type",
            field=models.CharField(
                choices=[("pickup", "Airport Pickup"), ("dropoff", "Airport Drop-off")],
                default="pickup",
                max_length=10,
            ),
        ),
    ]
