# Generated by Django 6.0.5 on 2026-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0003_business_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporateemployee",
            name="ride_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max completed rides per month.", null=True
            ),
        ),
    ]
