# Generated by Django 4.2.7 on 2026-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveprogram",
            name="incentive_type",
            field=models.CharField(
                choices=[
                    ("ride_count", "Complete X Rides"),
                    ("peak_hours", "Work During Peak Hours"),
                    ("consecutive_days", "Drive X Consecutive Days"),
                    ("rating", "Maintain High Rating"),
                    ("city_bonus", "Drive in Specific City"),
                    ("weekly_target", "Weekly Earnings Target"),
                    ("first_ride_bonus", "First Ride of the Day"),
                    ("intercity", "Complete Intercity Trip"),
                    ("seasonal", "Seasonal Bonus"),
                    ("holiday", "Holiday Bonus"),
                ],
                max_length=30,
            ),
        ),
    ]
