# Generated by Django 6.0.5 on 2026-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentives", "0004_incentive_engine_phase30"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveprogram",
            name="incentive_type",
            field=models.CharField(
                choices=[
                    ("daily_trip_target", "Daily Trip Target"),
                    ("weekly_trip_target", "Weekly Trip Target"),
                    ("peak_hour_bonus", "Peak-Hour Bonus"),
                    ("weekend_bonus", "Weekend Bonus"),
                    ("airport_bonus", "Airport Bonus"),
                    ("new_driver_bonus", "New Driver Bonus"),
                    ("referral_bonus", "Referral Bonus"),
                    ("consecutive_trips_bonus", "Consecutive Trips Bonus"),
                    ("ride_count", "Complete X Rides"),
                    ("peak_hours", "Work During Peak Hours"),
                    ("consecutive_days", "Drive X Consecutive Days"),
                    ("rating", "Maintain High Rating"),
                    ("city_bonus", "Drive in Specific City"),
                    ("weekly_target", "Weekly Earnings Target"),
                    ("first_ride_bonus", "First Ride of the Day"),
                    ("intercity", "Complete Intercity Trip"),
                    ("seasonal", "Seasonal Bonus"),
                    ("holiday", "Holiday Bonus"),
                    ("delivery_count", "Complete X Deliveries"),
                ],
                max_length=30,
            ),
        ),
    ]
