# Generated by Django 4.2.30 on 2026-06-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0012_payment_wallet_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deliveries", "0011_driverdeliverysettings_is_suspended_and_more"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantDocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_license_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "owner_id_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "logo_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "store_photo_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("business_license_notes", models.TextField(blank=True, default="")),
                ("owner_id_notes", models.TextField(blank=True, default="")),
                ("logo_notes", models.TextField(blank=True, default="")),
                ("store_photo_notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_review",
                        to="merchants.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FraudFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("excessive_cancellations", "Too Many Cancelled Orders"),
                            ("repeated_refunds", "Repeated Refund Requests"),
                            ("fake_location", "Fake Location Movement"),
                            ("failed_payments", "Multiple Failed Payments"),
                            ("early_delivery", "Courier Marked Delivered Too Early"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(default="medium", max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_flags",
                        to="deliveries.delivery",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_flags",
                        to="payments.paymentrecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fraud_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="fraud_status_idx"
                    ),
                    models.Index(fields=["user", "-created_at"], name="fraud_user_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryVerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pickup_pin_success", "Pickup PIN Success"),
                            ("pickup_pin_fail", "Pickup PIN Fail"),
                            ("dropoff_code_success", "Dropoff Code Success"),
                            ("dropoff_code_fail", "Dropoff Code Fail"),
                            ("proof_uploaded", "Proof of Delivery Uploaded"),
                            ("signature_uploaded", "Recipient Signature Uploaded"),
                            ("pickup_confirmed", "Pickup Confirmed by Customer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_verification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to="deliveries.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delivery", "-created_at"],
                        name="delivery_verify_evt_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerSavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=80)),
                ("address", models.CharField(max_length=500)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"], name="saved_addr_user_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("payment_change", "Payment Change"),
                            ("refund", "Refund"),
                            ("admin_action", "Admin Action"),
                            ("document_approval", "Document Approval"),
                            ("verification_event", "Verification Event"),
                            ("fraud_flag", "Fraud Flag"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("merchant", "Merchant"),
                            ("courier", "Courier"),
                            ("customer", "Customer"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("document", "Document"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="audit_entity_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="audit_action_idx"
                    ),
                ],
            },
        ),
    ]
