# Generated by Django 6.0.5 on 2026-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_delivery_instruction_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudflag",
            name="reason",
            field=models.CharField(
                choices=[
                    ("excessive_cancellations", "Too Many Cancelled Orders"),
                    ("repeated_refunds", "Repeated Refund Requests"),
                    ("fake_location", "Fake Location Movement"),
                    ("failed_payments", "Multiple Failed Payments"),
                    ("early_delivery", "Courier Marked Delivered Too Early"),
                    ("multi_account_device", "Multiple Accounts On One Device"),
                    ("pin_bruteforce", "PIN Brute-Force Attempts"),
                    ("ride_farming", "Suspected Ride Farming"),
                    ("delivery_farming", "Suspected Delivery Farming"),
                    ("integrity_fail", "Device Integrity Failure"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
