# Generated by Django 4.2.7 on 2026-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_ride_completed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["status"], name="ride_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["rider", "status"], name="ride_rider_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["driver", "status"], name="ride_driver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["-completed_at"], name="ride_completed_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["-created_at"], name="ride_created_idx"),
        ),
    ]
