# Generated by Django 4.2.7 on 2026-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_add_ride_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("driver_arriving", "Driver Arriving"),
                    ("driver_arrived", "Driver Arrived"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=30,
            ),
        ),
    ]
