# Generated by Django 4.2.7 on 2026-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_add_driver_arrived_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("scheduled", "Scheduled"),
                    ("driver_arriving", "Driver Arriving"),
                    ("driver_arrived", "Driver Arrived"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=30,
            ),
        ),
    ]
