# Generated by Django 6.0.5 on 2026-07-13 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0019_ride_no_show_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="dispatch_round",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Expanding search round: 1=2km, 2=5km, 3=10km, 4=city.",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="dispatch_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("searching", "Searching"),
                    ("offered", "Offered"),
                    ("assigned", "Assigned"),
                    ("no_driver_found", "No Driver Found"),
                ],
                db_index=True,
                default="idle",
                help_text="Smart-dispatch search state for rider/admin UX.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="search_radius_km",
            field=models.FloatField(
                blank=True,
                help_text="Radius (km) used for the current dispatch round.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="search_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When driver search began for this ride request.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DispatchOfferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_round", models.PositiveSmallIntegerField(default=1)),
                ("search_radius_km", models.FloatField(blank=True, null=True)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("eta_minutes", models.FloatField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("offered", "Offered"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("skipped", "Skipped"),
                            ("no_driver", "No Driver"),
                        ],
                        default="offered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_offer_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ride", "-created_at"], name="dispatch_log_ride_idx"
                    ),
                    models.Index(
                        fields=["result", "-created_at"], name="dispatch_log_result_idx"
                    ),
                ],
            },
        ),
    ]
