# Generated by Django on 2026-08-01

from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0007_ridecommissionconfig"),
        ("locations", "0004_citypricing"),
        ("rides", "0021_ride_corporate_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RidePricingSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_type", models.CharField(max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("city", "City Override"),
                            ("global_db", "Global DB"),
                            ("market_fallback", "Market Fallback"),
                        ],
                        default="market_fallback",
                        max_length=20,
                    ),
                ),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minimum_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billable_distance_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "distance_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "estimated_fare",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.3000"),
                        help_text="Platform commission share at ride creation.",
                        max_digits=5,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest effective timestamp of the applied configurations.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancellation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots_cancellation",
                        to="app_settings.cancellationfeeconfig",
                    ),
                ),
                (
                    "commission_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots_commission",
                        to="app_settings.ridecommissionconfig",
                    ),
                ),
                (
                    "city_pricing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots",
                        to="locations.citypricing",
                    ),
                ),
                (
                    "global_fare_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots",
                        to="app_settings.globalfareconfig",
                    ),
                ),
                (
                    "no_show_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots_no_show",
                        to="app_settings.noshowfeeconfig",
                    ),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_snapshot",
                        to="rides.ride",
                    ),
                ),
                (
                    "waiting_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_snapshots",
                        to="app_settings.waitingfeeconfig",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ride"], name="ride_snapshot_ride_idx"
                    ),
                    models.Index(
                        fields=["source"], name="ride_snapshot_source_idx"
                    ),
                ],
            },
        ),
    ]
