# Generated by Django 4.2.7 on 2026-08-02 02:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0022_ride_pricing_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridepricingsnapshot",
            name="app_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Platform fee captured at ride creation.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ridepricingsnapshot",
            name="driver_earning",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Driver earning captured at ride creation.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="ridepricingsnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
