# Generated by Django 4.2.7 on 2026-06-09 02:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
        ("rides", "0014_ride_cancellation_fee_ride_cancellation_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AirportLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("terminal_info", models.TextField(blank=True, default="")),
                (
                    "pickup_instructions",
                    models.TextField(blank=True, default="Meet at arrivals gate"),
                ),
                (
                    "surcharge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="cities.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=40)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("monthly_invoice", "Monthly Invoice"),
                            ("prepaid", "Prepaid Balance"),
                            ("per_ride", "Per Ride"),
                        ],
                        default="monthly_invoice",
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50000"), max_digits=12
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurgeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=4
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surge_zones",
                        to="cities.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-multiplier"],
            },
        ),
        migrations.CreateModel(
            name="SurgeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=4
                    ),
                ),
                (
                    "original_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "surge_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surge_history",
                        to="rides.ride",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="features.surgezone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "reported_by_role",
                    models.CharField(
                        choices=[("rider", "Rider"), ("driver", "Driver")],
                        default="rider",
                        max_length=10,
                    ),
                ),
                ("item_description", models.TextField()),
                ("item_category", models.CharField(default="other", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("searching", "Searching"),
                            ("found", "Found"),
                            ("returned", "Returned"),
                            ("not_found", "Not Found"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                (
                    "rider_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "driver_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="lost_found/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_item_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost_items",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AirportPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("arrival_time", models.DateTimeField()),
                ("destination", models.CharField(max_length=255)),
                ("destination_lat", models.FloatField(default=0)),
                ("destination_lng", models.FloatField(default=0)),
                (
                    "passenger_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "passenger_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("driver_assigned", "Driver Assigned"),
                            ("driver_en_route", "Driver En Route"),
                            ("waiting_at_airport", "Waiting at Airport"),
                            ("passenger_picked_up", "Passenger Picked Up"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                (
                    "fare_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="features.airportlocation",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airport_pickup_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airport_pickup",
                        to="rides.ride",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport_pickups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-arrival_time"],
            },
        ),
        migrations.CreateModel(
            name="DriverReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_code", models.CharField(max_length=30)),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500"), max_digits=10
                    ),
                ),
                ("required_rides", models.PositiveIntegerField(default=10)),
                ("completed_rides", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("qualified", "Qualified"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("referrer_paid", models.BooleanField(default=False)),
                ("referred_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_referral_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("referrer", "referred_driver")},
            },
        ),
        migrations.CreateModel(
            name="CorporateEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000"), max_digits=10
                    ),
                ),
                (
                    "monthly_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="features.corporateaccount",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "user")},
            },
        ),
    ]
