# Generated by Django 4.2.7 on 2026-05-19 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("xl", "XL"),
                            ("comfort", "Comfort"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_make",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "vehicle_plate",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "driver_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/photos/"
                    ),
                ),
                (
                    "vehicle_registration",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/vehicle_registration/"
                    ),
                ),
                (
                    "insurance_document",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/insurance/"
                    ),
                ),
                ("current_lat", models.FloatField(default=18.0735)),
                ("current_lng", models.FloatField(default=-15.9582)),
                ("driver_lat", models.FloatField(default=18.0735)),
                ("driver_lng", models.FloatField(default=-15.9582)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
