# Generated by Django 4.2.7 on 2026-05-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driverprofile_license_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="driver_category",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("diamond", "Diamond"),
                    ("elite", "Elite"),
                ],
                default="gold",
                max_length=20,
            ),
        ),
    ]
