# Generated by Django 4.2.7 on 2026-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driverprofile_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="insurance_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_registration_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
