# Generated by Django 4.2.7 on 2026-05-31 04:11

import django
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

_check_kw = (
    {"condition": models.Q(radius_km__gt=0)}
    if django.VERSION >= (5, 0)
    else {"check": models.Q(radius_km__gt=0)}
)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0009_add_ridestop_model"),
        ("drivers", "0005_driverprofile_insurance_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HeatmapZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                ("radius_km", models.FloatField(default=1.0)),
                ("intensity", models.FloatField(default=0.5)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="below_threshold_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="demotion_warning_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="driver_level",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("elite", "Elite"),
                ],
                default="bronze",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="reward_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_rides_accepted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_rides_cancelled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_rides_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="total_rides_received",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("live_chat", "Live Chat"),
                            ("contact_form", "Contact Form"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("ar", "Arabic")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("notifications_rides", models.BooleanField(default=True)),
                ("notifications_promotions", models.BooleanField(default=True)),
                ("notifications_system", models.BooleanField(default=True)),
                (
                    "gps_accuracy",
                    models.CharField(
                        choices=[
                            ("high", "High Accuracy"),
                            ("battery_saver", "Battery Saver"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                ("pin_lock", models.CharField(blank=True, default="", max_length=6)),
                ("biometric_enabled", models.BooleanField(default=False)),
                ("privacy_show_name", models.BooleanField(default=True)),
                ("privacy_show_photo", models.BooleanField(default=True)),
                ("privacy_show_vehicle", models.BooleanField(default=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Driver settings",
            },
        ),
        migrations.CreateModel(
            name="DriverFavoriteArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                ("radius_km", models.FloatField(default=3.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_areas",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("license", "Driver License"),
                            ("national_id", "National ID"),
                            ("insurance", "Insurance"),
                            ("vehicle_registration", "Vehicle Registration"),
                            ("profile_photo", "Profile Photo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="driver/documents/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverCompliment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professionalism", "Professionalism"),
                            ("clean_vehicle", "Clean Vehicle"),
                            ("safe_driving", "Safe Driving"),
                            ("friendliness", "Friendliness"),
                            ("punctuality", "Punctuality"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliments",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rides.ride"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drivers.achievement",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="driverfavoritearea",
            constraint=models.CheckConstraint(
                **_check_kw,
                name="positive_radius",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driverachievement",
            unique_together={("driver", "achievement")},
        ),
    ]
