# Generated by Django 4.2.30 on 2026-06-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0013_driverprofile_vehicle_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("license", "Driver License"),
                    ("national_id", "National ID"),
                    ("insurance", "Insurance"),
                    ("carte_grise", "Carte Grise"),
                    ("vignette", "Vignette"),
                    ("vehicle_registration", "Vehicle Registration (Legacy)"),
                    ("plate_number_photo", "Plate Number Photo"),
                    ("profile_photo", "Profile Photo"),
                ],
                max_length=30,
            ),
        ),
    ]
