# Generated by Django 4.2.7 on 2026-06-06 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField(default=18.0735)),
                ("pickup_lng", models.FloatField(default=-15.9582)),
                ("destination_lat", models.FloatField(default=18.0896)),
                ("destination_lng", models.FloatField(default=-15.9754)),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_phone", models.CharField(max_length=30)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("small", "Small Package"),
                            ("medium", "Medium Package"),
                            ("large", "Large Package"),
                        ],
                        default="small",
                        max_length=20,
                    ),
                ),
                ("package_description", models.TextField(blank=True, default="")),
                (
                    "package_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/packages/"
                    ),
                ),
                (
                    "proof_of_delivery",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/proof/"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("picked_up", "Picked Up"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("recipient_code_hash", models.CharField(max_length=255)),
                ("customer_notes", models.TextField(blank=True, default="")),
                ("driver_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="delivery_status_created_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="delivery_customer_status_idx",
                    ),
                    models.Index(
                        fields=["driver", "status"], name="delivery_driver_status_idx"
                    ),
                ],
            },
        ),
    ]
