# Generated by Django 4.2.30 on 2026-06-24 15:36

import deliveries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0009_delivery_pricing_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverdeliverysettings",
            name="delivery_cities",
            field=models.JSONField(
                blank=True, default=deliveries.models.default_delivery_cities
            ),
        ),
    ]
