# Generated by Django 4.2.30 on 2026-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0010_alter_delivery_cities_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverdeliverysettings",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverdeliverysettings",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
