# Generated by Django 4.2.30 on 2026-06-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0011_driverdeliverysettings_is_suspended_and_more"),
        ("safety", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetyincident",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_incidents",
                to="deliveries.delivery",
            ),
        ),
        migrations.AlterField(
            model_name="safetyincident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("sos", "SOS Emergency"),
                    ("safety_incident", "Safety Incident"),
                    ("report_driver", "Driver Report"),
                    ("report_rider", "Rider Report"),
                    ("report_courier", "Courier Report"),
                    ("report_merchant", "Merchant Report"),
                    ("delivery_problem", "Delivery Problem"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="safetyincident",
            index=models.Index(
                fields=["delivery", "-created_at"], name="safety_delivery_created_idx"
            ),
        ),
    ]
