# Generated by Django 6.0.5 on 2026-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0003_trip_safety_monitoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripsafetyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("long_stop", "Long Stop"),
                    ("route_deviation", "Route Deviation"),
                    ("long_trip", "Long Trip"),
                    ("driver_offline", "Driver Offline"),
                    ("safety_check", "Safety Check"),
                ],
                max_length=30,
            ),
        ),
    ]
