# Generated by Django 6.0.5 on 2026-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0004_rc3_model_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetyincident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("sos", "SOS Emergency"),
                    ("safety_incident", "Safety Incident"),
                    ("report_driver", "Driver Report"),
                    ("report_rider", "Rider Report"),
                    ("report_courier", "Courier Report"),
                    ("report_merchant", "Merchant Report"),
                    ("delivery_problem", "Delivery Problem"),
                    ("accident", "Accident"),
                    ("vehicle_breakdown", "Vehicle Breakdown"),
                    ("unsafe_passenger", "Unsafe Passenger"),
                    ("harassment", "Harassment"),
                    ("lost_property", "Lost Property"),
                    ("medical_emergency", "Medical Emergency"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
