from django.urls import path

from .chat_views import (
    delivery_call_session,
    delivery_chat_messages,
    delivery_chat_send,
    delivery_chat_templates,
)
from .views import (
    accept_delivery,
    admin_analytics,
    admin_disputes,
    arrive_pickup,
    available_deliveries,
    business_account_detail,
    business_accounts_list,
    cancel_delivery,
    confirm_delivery,
    confirm_stop,
    courier_account_dashboard,
    courier_earnings,
    courier_location,
    courier_onboarding,
    courier_profile,
    courier_profile_setup_submit,
    courier_vehicle_setup,
    create_dispute,
    customer_confirm_pickup,
    decline_delivery,
    delivery_detail,
    delivery_tracking,
    driver_delivery_mode,
    estimate_delivery_fare,
    my_deliveries,
    offer_timeout,
    pay_delivery,
    pickup_delivery,
    rate_delivery,
    report_delivery_problem,
    request_delivery,
    resolve_dispute,
    service_categories,
    start_delivery,
)


urlpatterns = [
    # Rider endpoints
    path("estimate/", estimate_delivery_fare, name="delivery-estimate"),
    path("request/", request_delivery, name="delivery-request"),
    path("mine/", my_deliveries, name="delivery-mine"),
    path("categories/", service_categories, name="delivery-categories"),
    path("<int:delivery_id>/", delivery_detail, name="delivery-detail"),
    path("<int:delivery_id>/tracking/", delivery_tracking, name="delivery-tracking"),
    path("<int:delivery_id>/cancel/", cancel_delivery, name="delivery-cancel"),
    path("<int:delivery_id>/confirm-pickup/", customer_confirm_pickup, name="delivery-confirm-pickup"),
    path("<int:delivery_id>/report/", report_delivery_problem, name="delivery-report"),
    path("<int:delivery_id>/rate/", rate_delivery, name="delivery-rate"),
    path("<int:delivery_id>/pay/", pay_delivery, name="delivery-pay"),
    path("<int:delivery_id>/dispute/", create_dispute, name="delivery-dispute"),
    path("<int:delivery_id>/chat/templates/", delivery_chat_templates, name="delivery-chat-templates"),
    path("<int:delivery_id>/chat/", delivery_chat_messages, name="delivery-chat-messages"),
    path("<int:delivery_id>/chat/send/", delivery_chat_send, name="delivery-chat-send"),
    path("<int:delivery_id>/call-session/", delivery_call_session, name="delivery-call-session"),

    # Driver endpoints
    path("available/", available_deliveries, name="delivery-available"),
    path("<int:delivery_id>/accept/", accept_delivery, name="delivery-accept"),
    path("<int:delivery_id>/decline/", decline_delivery, name="delivery-decline"),
    path("<int:delivery_id>/offer-timeout/", offer_timeout, name="delivery-offer-timeout"),
    path("<int:delivery_id>/arrive/", arrive_pickup, name="delivery-arrive"),
    path("<int:delivery_id>/pickup/", pickup_delivery, name="delivery-pickup"),
    path("<int:delivery_id>/start/", start_delivery, name="delivery-start"),
    path("<int:delivery_id>/confirm/", confirm_delivery, name="delivery-confirm"),
    path(
        "<int:delivery_id>/stops/<int:stop_id>/confirm/",
        confirm_stop,
        name="delivery-stop-confirm",
    ),
    path("driver/mode/", driver_delivery_mode, name="delivery-driver-mode"),
    path("courier/onboarding/", courier_onboarding, name="delivery-courier-onboarding"),
    path("courier/vehicle-setup/", courier_vehicle_setup, name="delivery-courier-vehicle-setup"),
    path(
        "courier/profile-setup/submit/",
        courier_profile_setup_submit,
        name="delivery-courier-profile-setup-submit",
    ),
    path("courier/profile/", courier_profile, name="delivery-courier-profile"),
    path("courier/account/", courier_account_dashboard, name="delivery-courier-account"),
    path("courier/location/", courier_location, name="delivery-courier-location"),
    path("courier/earnings/", courier_earnings, name="delivery-courier-earnings"),

    # Admin endpoints
    path("admin/analytics/", admin_analytics, name="delivery-admin-analytics"),
    path("admin/disputes/", admin_disputes, name="delivery-admin-disputes"),
    path(
        "admin/disputes/<int:dispute_id>/resolve/",
        resolve_dispute,
        name="delivery-admin-dispute-resolve",
    ),
    path("admin/business-accounts/", business_accounts_list, name="delivery-business-accounts"),
    path(
        "admin/business-accounts/<int:account_id>/",
        business_account_detail,
        name="delivery-business-account-detail",
    ),
]
