from django.urls import path

from .views import (
    save_payment_method,
    my_payment_methods,
    delete_payment_method,
    create_payment,
    my_payments,
    rider_mark_paid,
    driver_confirm_payment,
    my_payout_methods,
    owner_payout_summary,
    withdrawal_requests,
    request_withdrawal,
    approve_withdrawal,
    reject_withdrawal,
    save_payout_method,
    save_owner_payout_method,
    my_wallet,
    admin_wallet_adjustment,
    wallet_pay_ride,
)
from .wallet_views import (
    admin_approve_merchant_payout,
    admin_approve_refund,
    admin_payment_dashboard_view,
    admin_payment_records,
    admin_refund_queue,
    admin_reject_refund,
    courier_wallet_summary,
    create_refund_request,
    merchant_payout_history,
    merchant_request_payout,
    merchant_wallet_summary,
    my_payment_records,
    my_refund_requests,
    pay_delivery_wallet,
    pay_merchant_order,
    wallet_history,
    wallet_top_up_view,
)
from .webhooks import stripe_webhook

urlpatterns = [
    path("methods/save/", save_payment_method),
    path("methods/", my_payment_methods),
    path("methods/<int:method_id>/", delete_payment_method),

    path("create/", create_payment),
    path("my-payments/", my_payments),

    path("mark-paid/<int:ride_id>/", rider_mark_paid),
    path("confirm-payment/<int:ride_id>/", driver_confirm_payment),

    path("payout-methods/", my_payout_methods),
    path("payout-methods/save/", save_payout_method),
    path("owner-payout/", owner_payout_summary),
    path("owner-payout/save/", save_owner_payout_method),
    path("withdrawals/", withdrawal_requests),
    path("withdrawals/request/", request_withdrawal),
    path("withdrawals/<int:withdrawal_id>/approve/", approve_withdrawal),
    path("withdrawals/<int:withdrawal_id>/reject/", reject_withdrawal),
    path("wallet/", my_wallet),
    path("wallet/admin-adjustment/", admin_wallet_adjustment),
    path("wallet/pay-ride/<int:ride_id>/", wallet_pay_ride),
    path("wallet/top-up/", wallet_top_up_view),
    path("wallet/history/", wallet_history),
    path("wallet/pay-delivery/<int:delivery_id>/", pay_delivery_wallet),
    path("wallet/pay-merchant-order/<int:order_id>/", pay_merchant_order),
    path("records/", my_payment_records),
    path("courier/summary/", courier_wallet_summary),
    path("merchant/summary/", merchant_wallet_summary),
    path("merchant/payouts/request/", merchant_request_payout),
    path("merchant/payouts/history/", merchant_payout_history),
    path("refunds/", my_refund_requests),
    path("refunds/request/", create_refund_request),
    path("admin/dashboard/", admin_payment_dashboard_view),
    path("admin/records/", admin_payment_records),
    path("admin/refunds/", admin_refund_queue),
    path("admin/refunds/<int:refund_id>/approve/", admin_approve_refund),
    path("admin/refunds/<int:refund_id>/reject/", admin_reject_refund),
    path("admin/merchant-payouts/<int:payout_id>/approve/", admin_approve_merchant_payout),
    path("webhooks/stripe/", stripe_webhook),
]
