# Generated by Django 4.2.7 on 2026-05-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_remove_user_edited_at_remove_user_is_driver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="national_id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="users/national_ids/"
            ),
        ),
    ]
