# Generated by Django 4.2.7 on 2026-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_user_national_id_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pictures/"
            ),
        ),
    ]
