# Generated by Django 4.2.7 on 2026-06-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
        ("authapp", "0010_merge_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="cities.city",
            ),
        ),
    ]
