# Generated by Django 6.0.5 on 2026-06-09 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(blank=True, default="", max_length=50)),
                ("billing_address", models.TextField()),
                ("contact_person", models.CharField(max_length=120)),
                ("contact_phone", models.CharField(max_length=30)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("prepaid", "Prepaid"),
                            ("monthly", "Monthly Invoice"),
                        ],
                        default="prepaid",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                ("daily_limit", models.PositiveIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Package Damaged"),
                            ("lost", "Package Lost"),
                            ("late", "Delivery Too Late"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "photo_evidence",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/disputes/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund_full", "Full Refund"),
                            ("refund_partial", "Partial Refund"),
                            ("reject", "Dispute Rejected"),
                            ("warn_driver", "Driver Warning Issued"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_phone", models.CharField(max_length=30)),
                ("recipient_code_hash", models.CharField(max_length=255)),
                ("package_description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("arrived", "Arrived"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/stop_proofs/"
                    ),
                ),
            ],
            options={
                "ordering": ["stop_order"],
            },
        ),
        migrations.CreateModel(
            name="DriverDeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_mode_enabled", models.BooleanField(default=False)),
                (
                    "max_package_size",
                    models.CharField(
                        choices=[
                            ("document", "Document only"),
                            ("small", "Up to Small"),
                            ("medium", "Up to Medium"),
                            ("large", "All sizes"),
                        ],
                        default="large",
                        max_length=20,
                    ),
                ),
                ("accepts_food", models.BooleanField(default=True)),
                ("accepts_pharmacy", models.BooleanField(default=True)),
                ("accepts_fragile", models.BooleanField(default=True)),
                ("total_deliveries_completed", models.PositiveIntegerField(default=0)),
                (
                    "average_delivery_time_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "delivery_rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delivery",
            name="base_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="category_surcharge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="distance_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_earning",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="express_surcharge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="extra_stop_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="fragile_surcharge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_fragile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_temperature_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delivery",
            name="max_budget_mru",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="platform_commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="delivery",
            name="preparation_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="prescription_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="delivery",
            name="recipient_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="deliveries/signatures/"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="restaurant_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="delivery",
            name="scheduled_pickup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("food", "Food Delivery"),
                    ("package", "Package Delivery"),
                    ("document", "Document Delivery"),
                    ("pharmacy", "Pharmacy Delivery"),
                    ("shopping", "Shopping Delivery"),
                ],
                default="package",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="shopping_list",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="delivery",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="business_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="deliveries.businessaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["service_category", "status"],
                name="delivery_category_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["is_scheduled", "scheduled_pickup_at"],
                name="delivery_scheduled_idx",
            ),
        ),
        migrations.AddField(
            model_name="deliverydispute",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="deliveries.delivery",
            ),
        ),
        migrations.AddField(
            model_name="deliverydispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_delivery_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverydispute",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverystop",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="deliveries.delivery",
            ),
        ),
        migrations.AddField(
            model_name="driverdeliverysettings",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="deliverydispute",
            index=models.Index(
                fields=["status", "-created_at"], name="dispute_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverystop",
            index=models.Index(
                fields=["delivery", "status"], name="stop_delivery_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliverystop",
            unique_together={("delivery", "stop_order")},
        ),
        migrations.AddIndex(
            model_name="driverdeliverysettings",
            index=models.Index(
                fields=["delivery_mode_enabled"], name="driver_delivery_mode_idx"
            ),
        ),
    ]
