# Generated by Django 4.2.7 on 2026-06-09 02:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0014_ride_cancellation_fee_ride_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntercityRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=1, max_digits=8)),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Fare"), ("per_km", "Per Kilometer")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "fixed_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15"), max_digits=10
                    ),
                ),
                (
                    "toll_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_bidirectional", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intercity_arrivals",
                        to="cities.city",
                    ),
                ),
                (
                    "origin_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intercity_departures",
                        to="cities.city",
                    ),
                ),
            ],
            options={
                "ordering": ["origin_city__name", "destination_city__name"],
                "unique_together": {("origin_city", "destination_city")},
            },
        ),
        migrations.CreateModel(
            name="IntercityTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("searching", "Searching for Driver"),
                            ("scheduled", "Scheduled"),
                            ("driver_assigned", "Driver Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="searching",
                        max_length=20,
                    ),
                ),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_earning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                (
                    "luggage_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("is_round_trip", models.BooleanField(default=False)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercity_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercity_trip",
                        to="rides.ride",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intercity_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="intercity.intercityroute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntercityDriverMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("max_distance_km", models.PositiveIntegerField(default=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intercity_mode",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_routes",
                    models.ManyToManyField(blank=True, to="intercity.intercityroute"),
                ),
            ],
        ),
    ]
