import secrets
import re

import pytest
from unittest.mock import patch

from referrals.models import RiderReferralCode
from referrals.services.rider_referral_service import (
    RiderReferralService,
    ValidationResult,
)


def _clear_auto_generated_code(user):
    """Remove the referral code auto-generated by the post_save signal.

    The signal generates a code when a rider user is created.  Tests that
    need to manually create codes or test auto-generation logic should call
    this helper first to start from a clean state.
    """
    RiderReferralCode.objects.filter(rider=user).delete()


@pytest.mark.django_db
class TestGenerateReferralCode:
    """Tests for RiderReferralService.generate_referral_code"""

    def setup_method(self):
        self.service = RiderReferralService()

    def _create_rider(self):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        unique = secrets.token_hex(4)
        user = User.objects.create_user(
            email=f"rider_{unique}@test.com",
            password="testpass123",
            user_type="rider",
        )
        return user

    def test_generates_8_char_alphanumeric_code(self):
        """Code should be exactly 8 characters from [A-Z, 0-9]."""
        rider = self._create_rider()
        code = self.service.generate_referral_code(rider)

        assert len(code) == 8
        assert re.match(r"^[A-Z0-9]{8}$", code)

    def test_returns_existing_code_if_already_generated(self):
        """Calling generate twice should return the same code (idempotent)."""
        rider = self._create_rider()
        code1 = self.service.generate_referral_code(rider)
        code2 = self.service.generate_referral_code(rider)

        assert code1 == code2

    def test_stores_code_as_uppercase(self):
        """Code stored in the database should be uppercase."""
        rider = self._create_rider()
        code = self.service.generate_referral_code(rider)
        db_code = RiderReferralCode.objects.get(rider=rider).code

        assert db_code == db_code.upper()
        assert code == db_code

    def test_different_riders_get_different_codes(self):
        """Two different riders should get unique codes."""
        rider1 = self._create_rider()
        rider2 = self._create_rider()

        code1 = self.service.generate_referral_code(rider1)
        code2 = self.service.generate_referral_code(rider2)

        assert code1 != code2

    def test_raises_error_after_max_attempts_on_collision(self):
        """Should raise RuntimeError after 5 failed attempts."""
        rider = self._create_rider()
        # Remove the auto-generated code so we can test collision behaviour
        _clear_auto_generated_code(rider)

        # Create an existing code to cause collisions
        existing_rider = self._create_rider()
        existing_code = self.service.generate_referral_code(existing_rider)

        with patch.object(
            self.service,
            "_generate_random_code",
            return_value=existing_code,
        ):
            with pytest.raises(RuntimeError, match="Unable to generate"):
                self.service.generate_referral_code(rider)

    def test_retries_on_collision_and_succeeds(self):
        """Should retry on collision and succeed with a unique code."""
        rider = self._create_rider()
        # Remove the auto-generated code so we can test retry behaviour
        _clear_auto_generated_code(rider)

        # Create existing code
        existing_rider = self._create_rider()
        existing_code = self.service.generate_referral_code(existing_rider)

        # First 2 calls return the existing code (collision), third returns unique
        unique_code = "ZZZZ9999"
        call_count = {"n": 0}

        def mock_generate():
            call_count["n"] += 1
            if call_count["n"] <= 2:
                return existing_code
            return unique_code

        with patch.object(
            self.service, "_generate_random_code", side_effect=mock_generate
        ):
            code = self.service.generate_referral_code(rider)

        assert code == unique_code
        assert call_count["n"] == 3


@pytest.mark.django_db
class TestValidateReferralCode:
    """Tests for RiderReferralService.validate_referral_code"""

    def setup_method(self):
        self.service = RiderReferralService()

    def _create_rider(self, is_active=True):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        unique = secrets.token_hex(4)
        user = User.objects.create_user(
            email=f"rider_{unique}@test.com",
            password="testpass123",
            user_type="rider",
            is_active=is_active,
        )
        return user

    def test_invalid_format_too_short(self):
        """Codes shorter than 8 chars should fail with invalid_format."""
        referee = self._create_rider()
        result = self.service.validate_referral_code("ABC123", referee)

        assert not result.is_valid
        assert result.error_code == "invalid_format"
        assert result.referral_code_obj is None

    def test_invalid_format_too_long(self):
        """Codes longer than 8 chars should fail with invalid_format."""
        referee = self._create_rider()
        result = self.service.validate_referral_code("ABCDE12345", referee)

        assert not result.is_valid
        assert result.error_code == "invalid_format"

    def test_invalid_format_special_chars(self):
        """Codes with special characters should fail with invalid_format."""
        referee = self._create_rider()
        result = self.service.validate_referral_code("ABC!@#12", referee)

        assert not result.is_valid
        assert result.error_code == "invalid_format"

    def test_invalid_format_empty_string(self):
        """Empty string should fail with invalid_format."""
        referee = self._create_rider()
        result = self.service.validate_referral_code("", referee)

        assert not result.is_valid
        assert result.error_code == "invalid_format"

    def test_code_not_found(self):
        """Valid format but non-existent code should fail with code_not_found."""
        referee = self._create_rider()
        result = self.service.validate_referral_code("ZZZZ9999", referee)

        assert not result.is_valid
        assert result.error_code == "code_not_found"
        assert result.referral_code_obj is None

    def test_referrer_inactive(self):
        """Code belonging to inactive referrer should fail with referrer_inactive."""
        referrer = self._create_rider(is_active=False)
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        code = RiderReferralCode.objects.create(rider=referrer, code="AAAA1111")

        result = self.service.validate_referral_code("AAAA1111", referee)

        assert not result.is_valid
        assert result.error_code == "referrer_inactive"

    def test_self_referral(self):
        """Referee using their own code should fail with self_referral."""
        rider = self._create_rider()
        _clear_auto_generated_code(rider)
        code = RiderReferralCode.objects.create(rider=rider, code="BBBB2222")

        result = self.service.validate_referral_code("BBBB2222", rider)

        assert not result.is_valid
        assert result.error_code == "self_referral"

    def test_valid_code_returns_success(self):
        """Valid code with active referrer and different referee should succeed."""
        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="CCCC3333")

        result = self.service.validate_referral_code("CCCC3333", referee)

        assert result.is_valid
        assert result.error_code is None
        assert result.error_message is None
        assert result.referral_code_obj == code_obj

    def test_case_insensitive_lookup(self):
        """Lookup should work case-insensitively."""
        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="DDDD4444")

        result = self.service.validate_referral_code("dddd4444", referee)

        assert result.is_valid
        assert result.referral_code_obj == code_obj

    def test_mixed_case_lookup(self):
        """Mixed case input should resolve correctly."""
        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="EEEE5555")

        result = self.service.validate_referral_code("eEeE5555", referee)

        assert result.is_valid
        assert result.referral_code_obj == code_obj


@pytest.mark.django_db
class TestGetReferralInfo:
    """Tests for RiderReferralService.get_referral_info"""

    def setup_method(self):
        self.service = RiderReferralService()

    def _create_rider(self):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        unique = secrets.token_hex(4)
        user = User.objects.create_user(
            email=f"rider_{unique}@test.com",
            password="testpass123",
            user_type="rider",
        )
        return user

    def test_returns_referral_info_with_code(self):
        """Should return the rider's referral code."""
        from referrals.services.rider_referral_service import RiderReferralInfo

        rider = self._create_rider()
        info = self.service.get_referral_info(rider)

        assert isinstance(info, RiderReferralInfo)
        assert len(info.code) == 8
        assert re.match(r"^[A-Z0-9]{8}$", info.code)

    def test_returns_zero_referrals_and_credits_for_new_rider(self):
        """New rider should have 0 successful referrals and 0 credits."""
        from decimal import Decimal

        rider = self._create_rider()
        info = self.service.get_referral_info(rider)

        assert info.successful_referrals == 0
        assert info.total_credits_earned == Decimal("0.00")

    def test_counts_only_completed_referrals(self):
        """Should only count referrals with status 'completed'."""
        from decimal import Decimal
        from django.utils import timezone
        from referrals.models import RiderReferral, RiderReferralCode

        referrer = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="INFO1111")

        # Create completed referral
        referee1 = self._create_rider()
        RiderReferral.objects.create(
            referral_code=code_obj, referee=referee1, status="completed"
        )

        # Create pending referral (should not be counted)
        referee2 = self._create_rider()
        RiderReferral.objects.create(
            referral_code=code_obj, referee=referee2, status="pending"
        )

        info = self.service.get_referral_info(referrer)

        assert info.successful_referrals == 1

    def test_sums_active_and_used_referrer_credits(self):
        """Should sum original_amount for active/used credits with credit_type=referrer."""
        from decimal import Decimal
        from django.utils import timezone
        from referrals.models import RiderReferral, RiderReferralCode, RideCredit

        referrer = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="INFO2222")

        referee = self._create_rider()
        referral = RiderReferral.objects.create(
            referral_code=code_obj, referee=referee, status="completed"
        )

        # Active credit
        RideCredit.objects.create(
            rider=referrer,
            referral=referral,
            original_amount=Decimal("50.00"),
            remaining_amount=Decimal("50.00"),
            status="active",
            credit_type="referrer",
            expires_at=timezone.now() + timezone.timedelta(days=90),
        )

        # Used credit
        RideCredit.objects.create(
            rider=referrer,
            referral=referral,
            original_amount=Decimal("25.00"),
            remaining_amount=Decimal("0.00"),
            status="used",
            credit_type="referrer",
            expires_at=timezone.now() + timezone.timedelta(days=90),
        )

        # Expired credit (should NOT be counted)
        RideCredit.objects.create(
            rider=referrer,
            referral=referral,
            original_amount=Decimal("100.00"),
            remaining_amount=Decimal("0.00"),
            status="expired",
            credit_type="referrer",
            expires_at=timezone.now() - timezone.timedelta(days=1),
        )

        # Referee credit (should NOT be counted)
        RideCredit.objects.create(
            rider=referrer,
            referral=referral,
            original_amount=Decimal("50.00"),
            remaining_amount=Decimal("50.00"),
            status="active",
            credit_type="referee",
            expires_at=timezone.now() + timezone.timedelta(days=90),
        )

        info = self.service.get_referral_info(referrer)

        assert info.total_credits_earned == Decimal("75.00")

    def test_auto_generates_code_if_none_exists(self):
        """Should auto-generate a referral code if the rider doesn't have one yet."""
        rider = self._create_rider()
        # Remove auto-generated code from signal to test auto-generation logic
        _clear_auto_generated_code(rider)
        assert not RiderReferralCode.objects.filter(rider=rider).exists()

        info = self.service.get_referral_info(rider)

        assert info.code is not None
        assert len(info.code) == 8
        # Code should now exist in DB
        assert RiderReferralCode.objects.filter(rider=rider).exists()


@pytest.mark.django_db
class TestGetShareContent:
    """Tests for RiderReferralService.get_share_content"""

    def setup_method(self):
        self.service = RiderReferralService()

    def _create_rider(self):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        unique = secrets.token_hex(4)
        user = User.objects.create_user(
            email=f"rider_{unique}@test.com",
            password="testpass123",
            user_type="rider",
        )
        return user

    def test_returns_share_content_with_code(self):
        """Should return ShareContent with the rider's code."""
        from referrals.services.rider_referral_service import ShareContent

        rider = self._create_rider()
        content = self.service.get_share_content(rider)

        assert isinstance(content, ShareContent)
        assert len(content.code) == 8
        assert re.match(r"^[A-Z0-9]{8}$", content.code)

    def test_message_contains_code(self):
        """The shareable message should contain the referral code."""
        rider = self._create_rider()
        content = self.service.get_share_content(rider)

        assert content.code in content.message

    def test_message_contains_signup_link(self):
        """The shareable message should contain the signup link with the code."""
        rider = self._create_rider()
        content = self.service.get_share_content(rider)

        expected_link = f"https://yala.app/signup?ref={content.code}"
        assert expected_link in content.message

    def test_message_format(self):
        """The message should follow the expected format."""
        rider = self._create_rider()
        content = self.service.get_share_content(rider)

        expected = (
            f"Join Yala with my referral code {content.code}! "
            f"Sign up here: https://yala.app/signup?ref={content.code}"
        )
        assert content.message == expected

    def test_auto_generates_code_if_none_exists(self):
        """Should auto-generate a code if rider doesn't have one."""
        rider = self._create_rider()
        # Remove auto-generated code from signal to test auto-generation logic
        _clear_auto_generated_code(rider)
        assert not RiderReferralCode.objects.filter(rider=rider).exists()

        content = self.service.get_share_content(rider)

        assert content.code is not None
        assert RiderReferralCode.objects.filter(rider=rider).exists()

    def test_returns_existing_code(self):
        """Should use the existing code rather than generating a new one."""
        rider = self._create_rider()
        existing_code = self.service.generate_referral_code(rider)

        content = self.service.get_share_content(rider)

        assert content.code == existing_code


@pytest.mark.django_db
class TestRecordReferralSignup:
    """Tests for RiderReferralService.record_referral_signup"""

    def setup_method(self):
        self.service = RiderReferralService()

    def _create_rider(self, is_active=True):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        unique = secrets.token_hex(4)
        user = User.objects.create_user(
            email=f"rider_{unique}@test.com",
            password="testpass123",
            user_type="rider",
            is_active=is_active,
        )
        return user

    def test_records_referral_relationship(self):
        """Should create a RiderReferral linking referee to referrer's code."""
        from referrals.models import RiderReferral

        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        code_obj = RiderReferralCode.objects.create(rider=referrer, code="SIGN1111")

        referral = self.service.record_referral_signup(referee, "SIGN1111")

        assert isinstance(referral, RiderReferral)
        assert referral.referee == referee
        assert referral.referral_code == code_obj
        assert referral.status == "pending"

    def test_stores_device_id(self):
        """Should store the device_id for fraud detection."""
        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        RiderReferralCode.objects.create(rider=referrer, code="SIGN2222")

        referral = self.service.record_referral_signup(
            referee, "SIGN2222", device_id="device-abc-123"
        )

        assert referral.device_id == "device-abc-123"

    def test_default_device_id_is_empty(self):
        """device_id should default to empty string when not provided."""
        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        RiderReferralCode.objects.create(rider=referrer, code="SIGN3333")

        referral = self.service.record_referral_signup(referee, "SIGN3333")

        assert referral.device_id == ""

    def test_raises_value_error_on_invalid_code(self):
        """Should raise ValueError when code validation fails (bad format)."""
        referee = self._create_rider()

        with pytest.raises(ValueError, match="8 alphanumeric"):
            self.service.record_referral_signup(referee, "short")

    def test_raises_value_error_on_nonexistent_code(self):
        """Should raise ValueError when code does not exist."""
        referee = self._create_rider()

        with pytest.raises(ValueError, match="not recognized"):
            self.service.record_referral_signup(referee, "ZZZZ0000")

    def test_raises_value_error_on_self_referral(self):
        """Should raise ValueError on self-referral attempt."""
        rider = self._create_rider()
        _clear_auto_generated_code(rider)
        RiderReferralCode.objects.create(rider=rider, code="SELF1111")

        with pytest.raises(ValueError, match="own referral code"):
            self.service.record_referral_signup(rider, "SELF1111")

    def test_raises_value_error_on_inactive_referrer(self):
        """Should raise ValueError when referrer is inactive."""
        referrer = self._create_rider(is_active=False)
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        RiderReferralCode.objects.create(rider=referrer, code="INAC1111")

        with pytest.raises(ValueError, match="no longer valid"):
            self.service.record_referral_signup(referee, "INAC1111")

    def test_enforces_one_referral_per_account(self):
        """Should raise ValueError when referee already has a referral."""
        from referrals.models import RiderReferral

        referrer1 = self._create_rider()
        referrer2 = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer1)
        _clear_auto_generated_code(referrer2)
        code_obj1 = RiderReferralCode.objects.create(rider=referrer1, code="DUP11111")
        code_obj2 = RiderReferralCode.objects.create(rider=referrer2, code="DUP22222")

        # First referral succeeds
        self.service.record_referral_signup(referee, "DUP11111")

        # Second referral for the same referee should fail
        with pytest.raises(ValueError, match="already has a referral"):
            self.service.record_referral_signup(referee, "DUP22222")

    def test_case_insensitive_code_lookup(self):
        """Should work with case-insensitive code matching."""
        from referrals.models import RiderReferral

        referrer = self._create_rider()
        referee = self._create_rider()
        _clear_auto_generated_code(referrer)
        RiderReferralCode.objects.create(rider=referrer, code="CASE1111")

        referral = self.service.record_referral_signup(referee, "case1111")

        assert isinstance(referral, RiderReferral)
        assert referral.referee == referee
