from django.conf import settings
from django.db import models
from django.utils import timezone


class VehicleMaintenanceReminder(models.Model):
    TYPE_CHOICES = [
        ("oil_change", "Oil Change"),
        ("inspection", "Vehicle Inspection"),
        ("tires", "Tire Service"),
        ("insurance", "Insurance Renewal"),
        ("registration", "Registration Renewal"),
        ("other", "Other"),
    ]
    STATUS_CHOICES = [("upcoming", "Upcoming"), ("due", "Due"), ("completed", "Completed")]

    driver = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="maintenance_reminders"
    )
    reminder_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    title = models.CharField(max_length=160)
    due_date = models.DateField()
    due_odometer_km = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default="upcoming", db_index=True)
    notes = models.TextField(blank=True, default="")
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["status", "due_date"]

    def mark_completed(self):
        self.status = "completed"
        self.completed_at = timezone.now()
        self.save(update_fields=["status", "completed_at"])


class PlatformSetting(models.Model):
    """Key/value platform flags for executive controls (maintenance mode, etc.)."""

    key = models.CharField(max_length=64, unique=True)
    value = models.JSONField(default=dict, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="platform_setting_updates",
    )

    class Meta:
        ordering = ["key"]

    @classmethod
    def get_value(cls, key: str, default=None):
        row = cls.objects.filter(key=key).first()
        return row.value if row else default

    @classmethod
    def set_value(cls, key: str, value, user=None):
        row, _ = cls.objects.update_or_create(
            key=key,
            defaults={"value": value, "updated_by": user},
        )
        return row


class AIRecommendation(models.Model):
    """Human-in-the-loop operational suggestions generated by the AI ops engine."""

    CATEGORY_CHOICES = [
        ("reposition", "Reposition Drivers"),
        ("surge", "Surge Zone"),
        ("contact_driver", "Contact Driver"),
        ("add_couriers", "Add Couriers"),
        ("review_account", "Review Account"),
        ("incentive", "Increase Incentive"),
        ("fleet_health", "Fleet Health"),
        ("financial", "Financial Insight"),
        ("other", "Other"),
    ]
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("approved", "Approved"),
        ("dismissed", "Dismissed"),
        ("completed", "Completed"),
    ]

    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default="other")
    title = models.CharField(max_length=200)
    summary = models.TextField()
    explanation = models.JSONField(default=dict, blank=True)
    zone_lat = models.FloatField(null=True, blank=True)
    zone_lng = models.FloatField(null=True, blank=True)
    related_driver_id = models.IntegerField(null=True, blank=True)
    related_ride_id = models.IntegerField(null=True, blank=True)
    related_delivery_id = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending", db_index=True)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ai_recommendations_reviewed",
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "-created_at"]),
            models.Index(fields=["category", "status"]),
        ]

    def __str__(self):
        return f"{self.category}: {self.title[:60]}"


class OpsIncident(models.Model):
    """Operational incident tracking for launch and platform reliability."""

    SEVERITY_CHOICES = [
        ("critical", "Critical"),
        ("high", "High"),
        ("medium", "Medium"),
        ("low", "Low"),
    ]
    STATUS_CHOICES = [
        ("open", "Open"),
        ("investigating", "Investigating"),
        ("mitigated", "Mitigated"),
        ("resolved", "Resolved"),
    ]

    reference = models.CharField(max_length=32, unique=True, db_index=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, default="")
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default="medium", db_index=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="open", db_index=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="owned_ops_incidents",
    )
    root_cause = models.TextField(blank=True, default="")
    resolution = models.TextField(blank=True, default="")
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_ops_incidents",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "severity", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.reference} — {self.title[:50]}"


class OpsIncidentEvent(models.Model):
    """Timeline entries for operational incidents."""

    EVENT_TYPES = [
        ("note", "Note"),
        ("status_change", "Status Change"),
        ("assignment", "Assignment"),
        ("root_cause", "Root Cause"),
        ("resolution", "Resolution"),
    ]

    incident = models.ForeignKey(OpsIncident, on_delete=models.CASCADE, related_name="events")
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ops_incident_events",
    )
    event_type = models.CharField(max_length=20, choices=EVENT_TYPES, default="note")
    message = models.TextField()
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.incident.reference}: {self.event_type}"


class LaunchAlert(models.Model):
    """Persistent operational alerts for the launch control center."""

    ALERT_TYPES = [
        ("api_offline", "API Offline"),
        ("redis_offline", "Redis Offline"),
        ("database_offline", "Database Offline"),
        ("celery_stopped", "Celery Stopped"),
        ("high_error_rate", "High Error Rate"),
        ("high_cancellation_rate", "High Cancellation Rate"),
        ("large_withdrawal_queue", "Large Withdrawal Queue"),
        ("sos_event", "SOS Event"),
        ("expired_documents", "Expired Documents"),
        ("failed_payments", "Failed Payments"),
        ("other", "Other"),
    ]
    SEVERITY_CHOICES = OpsIncident.SEVERITY_CHOICES
    STATUS_CHOICES = [
        ("active", "Active"),
        ("acknowledged", "Acknowledged"),
        ("resolved", "Resolved"),
    ]

    alert_type = models.CharField(max_length=40, choices=ALERT_TYPES, db_index=True)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default="medium")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active", db_index=True)
    title = models.CharField(max_length=200)
    message = models.TextField(blank=True, default="")
    metadata = models.JSONField(default=dict, blank=True)
    acknowledged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="acknowledged_launch_alerts",
    )
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "alert_type", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.alert_type}: {self.title[:50]}"

