from django.urls import path

from .ai_operations_views import (
    ai_driver_performance,
    ai_financial_insights,
    ai_fleet_health,
    ai_hotspot_map,
    ai_operations_dashboard,
    ai_predictive_alerts,
    ai_recommendation_action,
    ai_recommendations_list,
    ai_recommendations_refresh,
    ai_smart_dispatch,
    ai_surge_monitor,
)
from .executive_views import (
    executive_account_action,
    executive_broadcast,
    executive_dashboard,
    executive_export,
    executive_finance,
    executive_live,
    executive_maintenance_mode,
    executive_map,
    executive_qa,
    executive_queues,
    executive_security,
    executive_support,
)
from .operations_center_views import (
    operations_broadcast_nearby,
    operations_cancel_delivery,
    operations_cancel_ride,
    operations_center_alerts,
    operations_center_analytics,
    operations_center_dashboard,
    operations_center_deliveries,
    operations_center_emergency,
    operations_center_fleet,
    operations_center_map,
    operations_center_timeline,
    operations_center_trips,
    operations_force_assign,
    operations_incident_action,
    operations_incident_export,
    operations_pause_driver,
    operations_reassign_delivery,
    operations_reassign_ride,
)
from .launch_views import (
    launch_alert_ack,
    launch_alert_resolve,
    launch_alerts_list,
    launch_checklist,
    launch_control_dashboard,
    launch_finance_export,
    launch_finance_reconciliation,
    launch_hub,
    launch_incident_detail,
    launch_incident_export,
    launch_incidents,
    launch_kpis,
    launch_onboarding,
    launch_support_queue,
)
from .views import complete_maintenance, maintenance_reminders

urlpatterns = [
    path("maintenance/", maintenance_reminders),
    path("maintenance/<int:reminder_id>/complete/", complete_maintenance),
    path("center/dashboard/", operations_center_dashboard),
    path("center/fleet/", operations_center_fleet),
    path("center/map/", operations_center_map),
    path("center/trips/", operations_center_trips),
    path("center/deliveries/", operations_center_deliveries),
    path("center/emergency/", operations_center_emergency),
    path("center/alerts/", operations_center_alerts),
    path("center/timeline/", operations_center_timeline),
    path("center/analytics/", operations_center_analytics),
    path("center/rides/<int:ride_id>/force-assign/", operations_force_assign),
    path("center/rides/<int:ride_id>/reassign/", operations_reassign_ride),
    path("center/rides/<int:ride_id>/cancel/", operations_cancel_ride),
    path("center/deliveries/<int:delivery_id>/reassign/", operations_reassign_delivery),
    path("center/deliveries/<int:delivery_id>/cancel/", operations_cancel_delivery),
    path("center/drivers/<int:driver_id>/pause/", operations_pause_driver),
    path("center/broadcast-nearby/", operations_broadcast_nearby),
    path("center/incidents/<int:incident_id>/action/", operations_incident_action),
    path("center/incidents/<int:incident_id>/export/", operations_incident_export),
    path("ai/dashboard/", ai_operations_dashboard),
    path("ai/smart-dispatch/", ai_smart_dispatch),
    path("ai/surge/", ai_surge_monitor),
    path("ai/hotspots/", ai_hotspot_map),
    path("ai/alerts/", ai_predictive_alerts),
    path("ai/driver-performance/", ai_driver_performance),
    path("ai/fleet-health/", ai_fleet_health),
    path("ai/recommendations/", ai_recommendations_list),
    path("ai/recommendations/refresh/", ai_recommendations_refresh),
    path("ai/recommendations/<int:recommendation_id>/action/", ai_recommendation_action),
    path("ai/financial/", ai_financial_insights),
    path("executive/dashboard/", executive_dashboard),
    path("executive/live/", executive_live),
    path("executive/finance/", executive_finance),
    path("executive/map/", executive_map),
    path("executive/queues/", executive_queues),
    path("executive/security/", executive_security),
    path("executive/support/", executive_support),
    path("executive/qa/", executive_qa),
    path("executive/reports/export/", executive_export),
    path("executive/broadcast/", executive_broadcast),
    path("executive/maintenance-mode/", executive_maintenance_mode),
    path("executive/account-action/", executive_account_action),
    path("launch/hub/", launch_hub),
    path("launch/control/", launch_control_dashboard),
    path("launch/alerts/", launch_alerts_list),
    path("launch/alerts/<int:alert_id>/ack/", launch_alert_ack),
    path("launch/alerts/<int:alert_id>/resolve/", launch_alert_resolve),
    path("launch/incidents/", launch_incidents),
    path("launch/incidents/<int:incident_id>/", launch_incident_detail),
    path("launch/incidents/<int:incident_id>/export/", launch_incident_export),
    path("launch/support/", launch_support_queue),
    path("launch/onboarding/", launch_onboarding),
    path("launch/finance/", launch_finance_reconciliation),
    path("launch/finance/export/", launch_finance_export),
    path("launch/kpis/", launch_kpis),
    path("launch/checklist/", launch_checklist),
]
