from django.urls import path

from .ai_operations_views import (
    ai_driver_performance,
    ai_financial_insights,
    ai_fleet_health,
    ai_hotspot_map,
    ai_operations_dashboard,
    ai_predictive_alerts,
    ai_recommendation_action,
    ai_recommendations_list,
    ai_recommendations_refresh,
    ai_smart_dispatch,
    ai_surge_monitor,
)
from .executive_views import (
    executive_account_action,
    executive_broadcast,
    executive_dashboard,
    executive_export,
    executive_finance,
    executive_live,
    executive_maintenance_mode,
    executive_map,
    executive_qa,
    executive_queues,
    executive_security,
    executive_support,
)
from .operations_center_views import (
    operations_broadcast_nearby,
    operations_cancel_delivery,
    operations_cancel_ride,
    operations_center_alerts,
    operations_center_analytics,
    operations_center_dashboard,
    operations_center_deliveries,
    operations_center_emergency,
    operations_center_fleet,
    operations_center_map,
    operations_center_timeline,
    operations_center_trips,
    operations_force_assign,
    operations_incident_action,
    operations_incident_export,
    operations_pause_driver,
    operations_reassign_delivery,
    operations_reassign_ride,
)
from .launch_views import (
    launch_alert_ack,
    launch_alert_resolve,
    launch_alerts_list,
    launch_checklist,
    launch_control_dashboard,
    launch_finance_export,
    launch_finance_reconciliation,
    launch_hub,
    launch_incident_detail,
    launch_incident_export,
    launch_incidents,
    launch_kpis,
    launch_onboarding,
    launch_support_queue,
)
from .beta_views import beta_ceo_report, beta_dashboard
from .beta_feedback_views import beta_feedback_dashboard, beta_feedback_detail, beta_feedback_list_create
from .fleet_performance_views import (
    fleet_ceo,
    fleet_dashboard,
    fleet_document_approve,
    fleet_document_reject,
    fleet_documents,
    fleet_driver_notify,
    fleet_driver_pause,
    fleet_driver_reactivate,
    fleet_driver_suspend,
    fleet_driver_training,
    fleet_drivers,
    fleet_overview,
    fleet_report_export,
)
from .finance_operations_views import (
    finance_accounting_report,
    finance_audit_trail,
    finance_operations_dashboard,
    finance_operations_export,
    finance_payment_providers,
    finance_reconciliation,
    finance_revenue_analytics,
    finance_withdrawals,
)
from .growth_expansion_views import growth_dashboard, growth_export
from .multi_city_views import (
    multi_city_city_detail,
    multi_city_cities,
    multi_city_dashboard,
    multi_city_export,
)
from .smart_pricing_dispatch_views import (
    smart_dispatch_analytics,
    smart_dispatch_rules,
    smart_engine_audit,
    smart_engine_ceo_dashboard,
    smart_engine_dashboard,
    smart_engine_flags,
    smart_pricing_rules,
    smart_pricing_simulate,
    smart_surge_config,
)
from .trust_safety_views import (
    trust_safety_audit,
    trust_safety_ceo_dashboard,
    trust_safety_dashboard,
    trust_safety_driver_profile,
    trust_safety_incident_detail,
    trust_safety_incidents,
    trust_safety_monitoring,
    trust_safety_reports,
    trust_safety_rider_profile,
)
from .incentive_engine_views import (
    incentive_bonus_export,
    incentive_campaign_detail,
    incentive_campaigns,
    incentive_ceo_dashboard,
    incentive_engine_dashboard,
    incentive_finance_dashboard,
    incentive_ops_dashboard,
    incentive_payout_action,
)
from .board_reporting_views import (
    board_business_kpis,
    board_executive_summary,
    board_financial_report,
    board_growth_report,
    board_operational_report,
    board_report_export,
    board_reporting_suite,
    board_risk_dashboard,
    board_strategic_planning,
)
from .bi_analytics_views import (
    bi_executive_analytics,
    bi_geographic_intelligence,
    bi_overview,
    bi_predictive_analytics,
    bi_report_export,
    bi_subject_area_detail,
    bi_subject_areas,
)
from .compliance_governance_views import (
    compliance_audit_action,
    compliance_audit_center,
    compliance_calendar,
    compliance_calendar_action,
    compliance_ceo_governance,
    compliance_dashboard,
    compliance_governance_suite,
    compliance_policy_action,
    compliance_policy_management,
    compliance_report_export,
    compliance_risk_action,
    compliance_risk_register,
)
from .merchant_platform_views import (
    merchant_platform_ceo,
    merchant_platform_commission,
    merchant_platform_dashboard,
    merchant_platform_finance,
    merchant_platform_merchant_action,
    merchant_platform_settlement_approve,
    merchant_platform_settlement_generate,
)
from .partner_platform_views import (
    partner_platform_action,
    partner_platform_ceo,
    partner_platform_dashboard,
    partner_platform_detail,
    partner_platform_finance,
    partner_platform_register,
    partner_platform_settlement_approve,
    partner_platform_settlement_generate,
    partner_platform_territory,
)
from .customer_growth_views import (
    customer_growth_campaign_create,
    customer_growth_ceo,
    customer_growth_dashboard,
    customer_growth_finance,
    customer_growth_flags,
    customer_growth_promo_create,
)
from .ceo_master_command_views import (
    ceo_master_action_approve_incentive,
    ceo_master_action_approve_onboarding,
    ceo_master_action_approve_payout,
    ceo_master_action_broadcast,
    ceo_master_action_freeze,
    ceo_master_ai_insights,
    ceo_master_dashboard,
    ceo_master_finance,
    ceo_master_fleet,
    ceo_master_growth,
    ceo_master_operations,
    ceo_master_overview,
    ceo_master_readiness,
    ceo_master_report_export,
)
from .launch_command_views import (
    command_alert_action,
    command_broadcast,
    command_ceo_export,
    command_dashboard,
    command_incident_action,
    command_incidents,
    command_notify,
    command_onboarding_pause,
)
from .business_views import (
    business_bi,
    business_compliance,
    business_compliance_export,
    business_corporate,
    business_corporate_account_action,
    business_corporate_detail,
    business_corporate_invoice,
    business_corporate_invoice_detail,
    business_corporate_invoice_export,
    business_corporate_invoices,
    business_crm,
    business_crm_profile,
    business_finance,
    business_finance_export,
    business_hub,
    business_incentives,
    business_marketing,
    business_marketing_analytics,
    business_marketing_campaigns,
    business_partner_detail,
    business_partners,
)
from .views import complete_maintenance, maintenance_reminders

urlpatterns = [
    path("maintenance/", maintenance_reminders),
    path("maintenance/<int:reminder_id>/complete/", complete_maintenance),
    path("center/dashboard/", operations_center_dashboard),
    path("center/fleet/", operations_center_fleet),
    path("center/map/", operations_center_map),
    path("center/trips/", operations_center_trips),
    path("center/deliveries/", operations_center_deliveries),
    path("center/emergency/", operations_center_emergency),
    path("center/alerts/", operations_center_alerts),
    path("center/timeline/", operations_center_timeline),
    path("center/analytics/", operations_center_analytics),
    path("center/rides/<int:ride_id>/force-assign/", operations_force_assign),
    path("center/rides/<int:ride_id>/reassign/", operations_reassign_ride),
    path("center/rides/<int:ride_id>/cancel/", operations_cancel_ride),
    path("center/deliveries/<int:delivery_id>/reassign/", operations_reassign_delivery),
    path("center/deliveries/<int:delivery_id>/cancel/", operations_cancel_delivery),
    path("center/drivers/<int:driver_id>/pause/", operations_pause_driver),
    path("center/broadcast-nearby/", operations_broadcast_nearby),
    path("center/incidents/<int:incident_id>/action/", operations_incident_action),
    path("center/incidents/<int:incident_id>/export/", operations_incident_export),
    path("ai/dashboard/", ai_operations_dashboard),
    path("ai/smart-dispatch/", ai_smart_dispatch),
    path("ai/surge/", ai_surge_monitor),
    path("ai/hotspots/", ai_hotspot_map),
    path("ai/alerts/", ai_predictive_alerts),
    path("ai/driver-performance/", ai_driver_performance),
    path("ai/fleet-health/", ai_fleet_health),
    path("ai/recommendations/", ai_recommendations_list),
    path("ai/recommendations/refresh/", ai_recommendations_refresh),
    path("ai/recommendations/<int:recommendation_id>/action/", ai_recommendation_action),
    path("ai/financial/", ai_financial_insights),
    path("executive/dashboard/", executive_dashboard),
    path("executive/live/", executive_live),
    path("executive/finance/", executive_finance),
    path("executive/map/", executive_map),
    path("executive/queues/", executive_queues),
    path("executive/security/", executive_security),
    path("executive/support/", executive_support),
    path("executive/qa/", executive_qa),
    path("executive/reports/export/", executive_export),
    path("executive/broadcast/", executive_broadcast),
    path("executive/maintenance-mode/", executive_maintenance_mode),
    path("executive/account-action/", executive_account_action),
    path("beta/dashboard/", beta_dashboard),
    path("beta/ceo-report/", beta_ceo_report),
    path("beta/feedback/dashboard/", beta_feedback_dashboard),
    path("beta/feedback/", beta_feedback_list_create),
    path("beta/feedback/<int:feedback_id>/", beta_feedback_detail),
    path("support/dashboard/", beta_feedback_dashboard),
    path("support/", beta_feedback_list_create),
    path("support/<int:feedback_id>/", beta_feedback_detail),
    path("fleet/dashboard/", fleet_dashboard),
    path("fleet/overview/", fleet_overview),
    path("fleet/drivers/", fleet_drivers),
    path("fleet/documents/", fleet_documents),
    path("fleet/ceo/", fleet_ceo),
    path("fleet/reports/export/", fleet_report_export),
    path("fleet/documents/<int:document_id>/approve/", fleet_document_approve),
    path("fleet/documents/<int:document_id>/reject/", fleet_document_reject),
    path("fleet/drivers/<int:driver_id>/suspend/", fleet_driver_suspend),
    path("fleet/drivers/<int:driver_id>/reactivate/", fleet_driver_reactivate),
    path("fleet/drivers/<int:driver_id>/pause/", fleet_driver_pause),
    path("fleet/drivers/<int:driver_id>/notify/", fleet_driver_notify),
    path("fleet/drivers/<int:driver_id>/training/", fleet_driver_training),
    path("launch/hub/", launch_hub),
    path("launch/control/", launch_control_dashboard),
    path("launch/alerts/", launch_alerts_list),
    path("launch/alerts/<int:alert_id>/ack/", launch_alert_ack),
    path("launch/alerts/<int:alert_id>/resolve/", launch_alert_resolve),
    path("launch/incidents/", launch_incidents),
    path("launch/incidents/<int:incident_id>/", launch_incident_detail),
    path("launch/incidents/<int:incident_id>/export/", launch_incident_export),
    path("launch/support/", launch_support_queue),
    path("launch/onboarding/", launch_onboarding),
    path("launch/finance/", launch_finance_reconciliation),
    path("launch/finance/export/", launch_finance_export),
    path("launch/kpis/", launch_kpis),
    path("launch/checklist/", launch_checklist),
    path("business/hub/", business_hub),
    path("business/finance/", business_finance),
    path("business/finance/export/", business_finance_export),
    path("business/crm/", business_crm),
    path("business/crm/profiles/<int:user_id>/", business_crm_profile),
    path("business/marketing/", business_marketing),
    path("business/marketing/analytics/", business_marketing_analytics),
    path("business/marketing/campaigns/", business_marketing_campaigns),
    path("business/incentives/", business_incentives),
    path("business/partners/", business_partners),
    path("business/partners/<int:partner_id>/", business_partner_detail),
    path("business/corporate/", business_corporate),
    path("business/corporate/invoices/", business_corporate_invoices),
    path("business/corporate/invoices/generate/", business_corporate_invoice),
    path("business/corporate/invoices/<int:invoice_id>/", business_corporate_invoice_detail),
    path("business/corporate/invoices/<int:invoice_id>/export/", business_corporate_invoice_export),
    path("business/corporate/<str:account_type>/<int:account_id>/", business_corporate_detail),
    path("business/corporate/<str:account_type>/<int:account_id>/action/", business_corporate_account_action),
    path("business/compliance/", business_compliance),
    path("business/compliance/export/", business_compliance_export),
    path("business/bi/", business_bi),
    path("business/finance/operations/", finance_operations_dashboard),
    path("business/finance/operations/reconciliation/", finance_reconciliation),
    path("business/finance/operations/providers/", finance_payment_providers),
    path("business/finance/operations/withdrawals/", finance_withdrawals),
    path("business/finance/operations/revenue/", finance_revenue_analytics),
    path("business/finance/operations/accounting/", finance_accounting_report),
    path("business/finance/operations/audit/", finance_audit_trail),
    path("business/finance/operations/export/", finance_operations_export),
    path("command/", command_dashboard),
    path("command/ceo/export/", command_ceo_export),
    path("command/broadcast/", command_broadcast),
    path("command/notify/", command_notify),
    path("command/onboarding/pause/", command_onboarding_pause),
    path("command/incidents/", command_incidents),
    path("command/incidents/<int:incident_id>/action/", command_incident_action),
    path("command/alerts/<int:alert_id>/action/", command_alert_action),
    path("growth/", growth_dashboard),
    path("growth/export/", growth_export),
    path("multi-city/", multi_city_dashboard),
    path("multi-city/cities/", multi_city_cities),
    path("multi-city/cities/<int:city_id>/", multi_city_city_detail),
    path("multi-city/export/", multi_city_export),
    path("smart-engine/", smart_engine_dashboard),
    path("smart-engine/flags/", smart_engine_flags),
    path("smart-engine/dispatch-rules/", smart_dispatch_rules),
    path("smart-engine/pricing-rules/", smart_pricing_rules),
    path("smart-engine/surge/", smart_surge_config),
    path("smart-engine/analytics/", smart_dispatch_analytics),
    path("smart-engine/simulate/", smart_pricing_simulate),
    path("smart-engine/ceo/", smart_engine_ceo_dashboard),
    path("smart-engine/audit/", smart_engine_audit),
    path("trust-safety/", trust_safety_dashboard),
    path("trust-safety/incidents/", trust_safety_incidents),
    path("trust-safety/incidents/<int:incident_id>/", trust_safety_incident_detail),
    path("trust-safety/monitoring/", trust_safety_monitoring),
    path("trust-safety/drivers/<int:user_id>/", trust_safety_driver_profile),
    path("trust-safety/riders/<int:user_id>/", trust_safety_rider_profile),
    path("trust-safety/ceo/", trust_safety_ceo_dashboard),
    path("trust-safety/reports/", trust_safety_reports),
    path("trust-safety/audit/", trust_safety_audit),
    path("incentive-engine/", incentive_engine_dashboard),
    path("incentive-engine/campaigns/", incentive_campaigns),
    path("incentive-engine/campaigns/<int:campaign_id>/", incentive_campaign_detail),
    path("incentive-engine/ops/", incentive_ops_dashboard),
    path("incentive-engine/ceo/", incentive_ceo_dashboard),
    path("incentive-engine/finance/", incentive_finance_dashboard),
    path("incentive-engine/payouts/<int:payment_id>/action/", incentive_payout_action),
    path("incentive-engine/export/", incentive_bonus_export),

    path("merchant-platform/", merchant_platform_dashboard),
    path("merchant-platform/ceo/", merchant_platform_ceo),
    path("merchant-platform/finance/", merchant_platform_finance),
    path("merchant-platform/merchants/<int:merchant_id>/action/", merchant_platform_merchant_action),
    path("merchant-platform/merchants/<int:merchant_id>/commission/", merchant_platform_commission),
    path("merchant-platform/merchants/<int:merchant_id>/settlements/generate/", merchant_platform_settlement_generate),
    path("merchant-platform/settlements/<int:settlement_id>/approve/", merchant_platform_settlement_approve),

    path("partner-platform/", partner_platform_dashboard),
    path("partner-platform/register/", partner_platform_register),
    path("partner-platform/ceo/", partner_platform_ceo),
    path("partner-platform/finance/", partner_platform_finance),
    path("partner-platform/partners/<int:partner_id>/", partner_platform_detail),
    path("partner-platform/partners/<int:partner_id>/action/", partner_platform_action),
    path("partner-platform/partners/<int:partner_id>/territories/", partner_platform_territory),
    path("partner-platform/partners/<int:partner_id>/settlements/generate/", partner_platform_settlement_generate),
    path("partner-platform/settlements/<int:settlement_id>/approve/", partner_platform_settlement_approve),

    path("customer-growth/", customer_growth_dashboard),
    path("customer-growth/ceo/", customer_growth_ceo),
    path("customer-growth/finance/", customer_growth_finance),
    path("customer-growth/flags/", customer_growth_flags),
    path("customer-growth/promos/", customer_growth_promo_create),
    path("customer-growth/campaigns/", customer_growth_campaign_create),

    # CEO Master Command Center (Phase 34)
    path("ceo-master/", ceo_master_dashboard),
    path("ceo-master/overview/", ceo_master_overview),
    path("ceo-master/finance/", ceo_master_finance),
    path("ceo-master/operations/", ceo_master_operations),
    path("ceo-master/growth/", ceo_master_growth),
    path("ceo-master/fleet/", ceo_master_fleet),
    path("ceo-master/ai-insights/", ceo_master_ai_insights),
    path("ceo-master/readiness/", ceo_master_readiness),
    path("ceo-master/reports/<str:report_type>/export/", ceo_master_report_export),
    path("ceo-master/actions/broadcast/", ceo_master_action_broadcast),
    path("ceo-master/actions/freeze/", ceo_master_action_freeze),
    path("ceo-master/actions/approve-payout/", ceo_master_action_approve_payout),
    path("ceo-master/actions/approve-onboarding/", ceo_master_action_approve_onboarding),
    path("ceo-master/actions/approve-incentive/", ceo_master_action_approve_incentive),

    # Board & Investor Reporting Suite (Phase 35)
    path("board-reports/", board_reporting_suite),
    path("board-reports/executive-summary/", board_executive_summary),
    path("board-reports/business-kpis/", board_business_kpis),
    path("board-reports/financial/", board_financial_report),
    path("board-reports/operational/", board_operational_report),
    path("board-reports/growth/", board_growth_report),
    path("board-reports/risk/", board_risk_dashboard),
    path("board-reports/strategic/", board_strategic_planning),
    path("board-reports/<str:report_type>/export/", board_report_export),

    # Business Intelligence & Data Warehouse (Phase 37)
    path("bi/", bi_overview),
    path("bi/subject-areas/", bi_subject_areas),
    path("bi/subject-areas/<str:area>/", bi_subject_area_detail),
    path("bi/executive-analytics/", bi_executive_analytics),
    path("bi/geographic-intelligence/", bi_geographic_intelligence),
    path("bi/predictive-analytics/", bi_predictive_analytics),
    path("bi/reports/<str:report_type>/export/", bi_report_export),

    # Compliance & Governance Center (Phase 36)
    path("compliance-governance/", compliance_governance_suite),
    path("compliance-governance/dashboard/", compliance_dashboard),
    path("compliance-governance/audits/", compliance_audit_center),
    path("compliance-governance/audits/<int:audit_id>/action/", compliance_audit_action),
    path("compliance-governance/policies/", compliance_policy_management),
    path("compliance-governance/policies/<int:policy_id>/action/", compliance_policy_action),
    path("compliance-governance/risks/", compliance_risk_register),
    path("compliance-governance/risks/<int:risk_id>/action/", compliance_risk_action),
    path("compliance-governance/calendar/", compliance_calendar),
    path("compliance-governance/calendar/<int:event_id>/action/", compliance_calendar_action),
    path("compliance-governance/ceo-governance/", compliance_ceo_governance),
    path("compliance-governance/reports/<str:report_type>/export/", compliance_report_export),
]
