# Generated by Django 4.2.7 on 2026-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="license_file",
            field=models.FileField(
                blank=True, null=True, upload_to="drivers/licenses/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="plate_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="car_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Regular"),
                    ("xl", "XL"),
                    ("comfort", "Comfort"),
                    ("share", "Share"),
                ],
                default="regular",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="current_lat",
            field=models.FloatField(blank=True, default=18.0735, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="current_lng",
            field=models.FloatField(blank=True, default=-15.9582, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="driver_lat",
            field=models.FloatField(blank=True, default=18.0735, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="driver_lng",
            field=models.FloatField(blank=True, default=-15.9582, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_make",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_registration",
            field=models.FileField(
                blank=True, null=True, upload_to="drivers/registrations/"
            ),
        ),
    ]
