# Generated by Django 4.2.7 on 2026-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driverprofile_driver_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="terms_version",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
