# Generated by Django 4.2.7 on 2026-06-10 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivers", "0008_driverprofile_application_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="qr_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="qr_code_image",
            field=models.FileField(
                blank=True, null=True, upload_to="drivers/qr_codes/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="qr_code_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=36, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="QRCodeAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("regenerated", "Regenerated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_qr_uuid", models.CharField(blank=True, max_length=36, null=True)),
                ("new_qr_uuid", models.CharField(max_length=36)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_audit_logs",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("inactive_driver", "Inactive Driver"),
                            ("invalid_code", "Invalid Code"),
                            ("forged_code", "Forged Code"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_records",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
                "indexes": [
                    models.Index(
                        fields=["-scanned_at"], name="drivers_ver_scanned_2c9c7a_idx"
                    ),
                    models.Index(
                        fields=["rider", "-scanned_at"],
                        name="drivers_ver_rider_i_5de80f_idx",
                    ),
                    models.Index(
                        fields=["driver", "-scanned_at"],
                        name="drivers_ver_driver__9f9dd0_idx",
                    ),
                ],
            },
        ),
    ]
