# Generated by Django 4.2.7 on 2026-07-09 04:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0019_ride_no_show_at"),
        ("drivers", "0020_driverprofile_total_rides_no_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("ride_count", "Complete X Rides"),
                            ("earnings_target", "Earn X MRU"),
                            ("acceptance_rate", "Maintain X% Acceptance Rate"),
                            ("zero_cancellations", "Zero Cancellations"),
                            ("airport_rides", "Complete X Airport Rides"),
                            ("weekend_rides", "Complete X Weekend Rides"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=10)),
                ("reward_points", models.PositiveIntegerField(default=0)),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "badge_icon",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-starts_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="reward_tier",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("diamond", "Diamond"),
                ],
                db_index=True,
                default="bronze",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DriverPointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ride_complete", "Ride Completed"),
                            ("five_star_rating", "5-Star Rating"),
                            ("peak_hour_ride", "Peak-Hour Ride"),
                            ("airport_ride", "Airport Ride"),
                            ("long_distance_ride", "Long-Distance Ride"),
                            ("referral_completed", "Referral Completed"),
                            ("driver_cancellation", "Driver Cancellation"),
                            ("fraud_confirmed", "Fraud Confirmed"),
                            ("unsafe_driving_complaint", "Unsafe Driving Complaint"),
                            ("challenge_bonus", "Challenge Bonus"),
                            ("monthly_bonus", "Monthly Reward Bonus"),
                            ("manual_adjustment", "Manual Adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "reference_ride",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverMonthlyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("top_driver", "Top Driver"),
                            ("top_earner", "Top Earner"),
                            ("most_improved", "Most Improved"),
                            ("highest_rated", "Highest Rated"),
                            ("featured_driver", "Featured Driver"),
                        ],
                        max_length=30,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "badge_icon",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("priority_boost", models.PositiveSmallIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_rewards",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-awarded_at"],
                "unique_together": {("driver", "reward_type", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="DriverChallengeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paid", "Paid"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bonus_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="drivers.weeklychallenge",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("driver", "challenge")},
            },
        ),
    ]
