# Generated by Django 6.0.5 on 2026-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0021_driver_rewards_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="available_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When the driver last went online (fair rotation).",
                null=True,
            ),
        ),
    ]
