# Generated by Django 6.0.5 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_launch_preparation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ride_corporate", "Ride Corporate"),
                            ("delivery_business", "Delivery Business"),
                        ],
                        max_length=30,
                    ),
                ),
                ("account_id", models.PositiveIntegerField()),
                ("company_name", models.CharField(max_length=200)),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ride_count", models.PositiveIntegerField(default=0)),
                ("delivery_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push Notification"),
                            ("email", "Email"),
                            ("promo", "Promo Code"),
                            ("referral", "Referral"),
                            ("incentive", "Driver/Courier Incentive"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_riders", "All Riders"),
                            ("all_drivers", "All Drivers"),
                            ("all_couriers", "All Couriers"),
                            ("vip", "VIP Customers"),
                            ("city", "City Segment"),
                            ("custom", "Custom"),
                        ],
                        default="all_riders",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("promo_code_id", models.IntegerField(blank=True, null=True)),
                ("city_id", models.IntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpsCustomerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_vip", models.BooleanField(db_index=True, default=False)),
                (
                    "vip_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_blacklisted", models.BooleanField(db_index=True, default=False)),
                ("blacklist_reason", models.TextField(blank=True, default="")),
                ("blacklist_until", models.DateTimeField(blank=True, null=True)),
                ("complaints_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="airecommendation",
            new_name="operations__status_391a7d_idx",
            old_name="operations__status_8a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="airecommendation",
            new_name="operations__categor_b4a849_idx",
            old_name="operations__categor_3d4e5f_idx",
        ),
        migrations.RenameIndex(
            model_name="launchalert",
            new_name="operations__status_52ffab_idx",
            old_name="operations__status_0d8caa_idx",
        ),
        migrations.RenameIndex(
            model_name="opsincident",
            new_name="operations__status_50f643_idx",
            old_name="operations__status_6a0f6d_idx",
        ),
        migrations.AddField(
            model_name="marketingcampaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketing_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opscustomerrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opscustomerrecord",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ops_customer_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
