# Generated by Django 6.0.5 on 2026-07-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_corporateinvoice_billing_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="betafeedback",
            new_name="operations__status_cf430e_idx",
            old_name="operations__status_6a0f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="betafeedback",
            new_name="operations__app_typ_e2a691_idx",
            old_name="operations__app_ty_5c8b91_idx",
        ),
    ]
