# Generated by Django 6.0.5 on 2026-07-22 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_multicity_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("company", "Company Policy"),
                            ("security", "Security Policy"),
                            ("privacy", "Privacy Policy"),
                            ("operational", "Operational Procedure"),
                            ("driver_handbook", "Driver Handbook"),
                            ("courier_handbook", "Courier Handbook"),
                            ("merchant_handbook", "Merchant Handbook"),
                            ("employee_handbook", "Employee Handbook"),
                            ("terms", "Terms of Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=20)),
                ("content_url", models.URLField(blank=True, default="")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/policies/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("review_pending", "Review Pending"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(db_index=True)),
                ("acknowledgement_required", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "-review_date"],
                "unique_together": {("category", "version")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Audit"),
                            ("financial", "Financial Audit"),
                            ("security", "Security Audit"),
                            ("operational", "Operational Audit"),
                            ("it", "IT Audit"),
                            ("compliance", "Compliance Audit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("pending_findings", "Pending Findings"),
                            ("closed", "Closed"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("findings", models.JSONField(blank=True, default=list)),
                ("corrective_actions", models.JSONField(blank=True, default=list)),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/audit_evidence/"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_compliance_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_date"],
                        name="operations__status_f70bc9_idx",
                    ),
                    models.Index(
                        fields=["audit_type", "status"],
                        name="operations__audit_t_b4552a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("insurance_renewal", "Insurance Renewal"),
                            ("license_renewal", "Business License Renewal"),
                            ("tax_filing", "Tax Filing"),
                            ("financial_reporting", "Financial Reporting"),
                            ("policy_review", "Policy Review"),
                            ("security_review", "Security Review"),
                            ("annual_audit", "Annual Audit"),
                            ("compliance_deadline", "Compliance Deadline"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("due_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("due_soon", "Due Soon"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=15,
                    ),
                ),
                (
                    "related_entity_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("related_entity_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_compliance_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "status"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_date"],
                        name="operations__status_7493aa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strategic", "Strategic"),
                            ("operational", "Operational"),
                            ("financial", "Financial"),
                            ("cybersecurity", "Cybersecurity"),
                            ("legal", "Legal"),
                            ("reputation", "Reputation"),
                            ("compliance", "Compliance"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mitigation", models.TextField(blank=True, default="")),
                ("review_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("mitigated", "Mitigated"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_compliance_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "category", "-review_date"],
                        name="operations__status_e922de_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="operations.policydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-acknowledged_at"],
                "unique_together": {("user", "policy")},
            },
        ),
    ]
