# Generated by Django 6.0.5 on 2026-07-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_policydocument_complianceaudit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsShiftHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("city_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("open_incidents_summary", models.TextField(blank=True, default="")),
                ("delayed_rides_summary", models.TextField(blank=True, default="")),
                ("drivers_attention_summary", models.TextField(blank=True, default="")),
                ("payment_system_concerns", models.TextField(blank=True, default="")),
                ("pending_escalations", models.TextField(blank=True, default="")),
                ("important_notes", models.TextField(blank=True, default="")),
                ("follow_up_notes", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incoming_operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_handovers_incoming",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outgoing_operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ops_handovers_outgoing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="operations__status_d41a7a_idx",
                    )
                ],
            },
        ),
    ]
