# Generated by Django 6.0.5 on 2026-08-01 05:44

from decimal import Decimal

from django.utils import timezone
from django.db import migrations


SEED_FARES = [
    {"ride_type": "Regular", "base_fare": Decimal("175.00"), "per_km": Decimal("20.00"), "minimum_fare": Decimal("175.00")},
    {"ride_type": "XL", "base_fare": Decimal("225.00"), "per_km": Decimal("25.00"), "minimum_fare": Decimal("225.00")},
    {"ride_type": "Comfort", "base_fare": Decimal("275.00"), "per_km": Decimal("30.00"), "minimum_fare": Decimal("275.00")},
    {"ride_type": "Share", "base_fare": Decimal("150.00"), "per_km": Decimal("15.00"), "minimum_fare": Decimal("150.00")},
]


def seed_pricing_configs(apps, schema_editor):
    GlobalFareConfig = apps.get_model("app_settings", "GlobalFareConfig")
    WaitingFeeConfig = apps.get_model("app_settings", "WaitingFeeConfig")
    CancellationFeeConfig = apps.get_model("app_settings", "CancellationFeeConfig")
    NoShowFeeConfig = apps.get_model("app_settings", "NoShowFeeConfig")
    RideCommissionConfig = apps.get_model("app_settings", "RideCommissionConfig")

    now = timezone.now()

    for fare in SEED_FARES:
        if not GlobalFareConfig.objects.filter(
            ride_type=fare["ride_type"], is_active=True
        ).exists():
            GlobalFareConfig.objects.create(
                ride_type=fare["ride_type"],
                base_fare=fare["base_fare"],
                per_km=fare["per_km"],
                minimum_fare=fare["minimum_fare"],
                is_active=True,
                effective_from=now,
            )

    if not WaitingFeeConfig.objects.filter(is_active=True).exists():
        WaitingFeeConfig.objects.create(
            free_minutes=3,
            per_minute_fee=Decimal("50.00"),
            max_wait_minutes=5,
            arrive_max_distance_m=350,
            no_show_max_distance_m=150,
            is_active=True,
            effective_from=now,
        )

    if not CancellationFeeConfig.objects.filter(is_active=True).exists():
        CancellationFeeConfig.objects.create(
            free_window_minutes=2,
            en_route_fee=Decimal("50.00"),
            arrived_fee=Decimal("75.00"),
            driver_penalty=Decimal("150.00"),
            is_active=True,
            effective_from=now,
        )

    if not NoShowFeeConfig.objects.filter(is_active=True).exists():
        NoShowFeeConfig.objects.create(
            rider_fee=Decimal("75.00"),
            driver_compensation=Decimal("75.00"),
            wait_minutes_threshold=5,
            max_distance_m=150,
            is_active=True,
            effective_from=now,
        )

    if not RideCommissionConfig.objects.filter(is_active=True).exists():
        RideCommissionConfig.objects.create(
            platform_percent=Decimal("0.3000"),
            driver_percent=Decimal("0.7000"),
            is_active=True,
            effective_from=now,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0002_cancellationfeeconfig_globalfareconfig_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_pricing_configs, migrations.RunPython.noop),
    ]
