# Generated by Django 4.2.7 on 2026-08-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0008_pricingauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
