/**
 * YALA Driver UI component aliases
 * Thin re-exports over the shared design-system for Driver-specific naming.
 * Prefer importing from `../../design-system` when adding new screens (Mission 4+).
 */
export {
  PrimaryButton,
  SecondaryButton,
  OutlinedButton,
  TextButton,
  IconButton,
  FloatingActionButton,
  DriverCard,
  Section as DriverSection,
  StatusChip,
  StatCard,
  SettingsRow,
  EmptyState,
  ErrorState,
  LoadingSkeleton,
  OfflineState,
  NoDataState,
  ConfirmationDialog,
  BottomSheet,
  Snackbar,
  Toast,
  ProfileHeader,
  VehicleCard,
  DocumentCard,
  TripCard,
  EarningsCard,
  WalletCard,
  SupportCard,
  AppBar as DriverAppBar,
  TopAppBar,
  BottomNavigation,
  ScreenContainer,
  ScrollablePage,
  StickyFooter,
  FloatingActionArea,
  Page as DriverPage,
  Avatar,
  ListRow,
  Icon,
  OnlineStatus,
  ApprovalStatus,
  DocumentStatus,
  TripStatus,
  RideStatus,
  TextInput,
  SearchBar,
  PhoneInput,
  OTPInput,
  Dropdown,
  SegmentedControl,
  Switch,
  Checkbox,
  RadioButton,
  InfoRow,
  SectionHeader,
  ActionRow,
  QuickActionTile,
  RetryView,
  PermissionDenied,
  Modal,
  ActionSheet,
  ProgressIndicator,
  Badge,
} from "../../design-system";

export { default as DriverShell } from "../components/DriverShell";
export { default as DriverNavigation } from "../DriverNavigation";
