# Generated by Django 4.2.7 on 2026-06-05 19:06

import authapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0008_phone_verification_and_rejection_reason"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authapp.models.UserManager()),
            ],
        ),
    ]
