# Generated by Django 4.2.30 on 2026-07-03 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0016_rename_rider_terms_to_ride_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[("phone", "Phone"), ("email", "Email")], max_length=10
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("code_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("requested_device_info", models.TextField(blank=True, default="")),
                (
                    "reset_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("reset_device_info", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identifier", "-created_at"],
                        name="authapp_pas_identif_db5e79_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="authapp_pas_user_id_f1e4c4_idx",
                    ),
                ],
            },
        ),
    ]
