# Generated by Django 6.0.5 on 2026-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_fcm_app_type_history_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmtoken",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("rider", "Rider"),
                    ("driver", "Driver"),
                    ("delivery", "Delivery"),
                    ("web", "Web"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
