# Generated by Django 4.2.7 on 2026-05-25 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0006_driverpayoutmethod_withdrawalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverpayoutmethod",
            name="payout_type",
            field=models.CharField(
                choices=[
                    ("bank_account", "Bank Account"),
                    ("card", "Card"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masravi"),
                    ("seddad", "Seddad"),
                ],
                default="bank_account",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masravi"),
                    ("seddad", "Seddad"),
                    ("test", "Test"),
                ],
                default="test",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masravi"),
                    ("seddad", "Seddad"),
                    ("cash", "Cash"),
                ],
                default="card",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="OwnerPayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("bankily", "Bankily"),
                            ("masrvi", "Masravi"),
                            ("seddad", "Seddad"),
                        ],
                        default="bank_account",
                        max_length=30,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("wallet_id", models.CharField(blank=True, default="", max_length=100)),
                ("is_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_payout_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
