# Generated by Django 4.2.30 on 2026-06-24 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0010_alter_delivery_cities_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merchants", "0001_initial"),
        ("payments", "0011_alter_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("merchant", "Merchant Order"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "courier_rate",
                    models.DecimalField(decimal_places=4, default=0.8, max_digits=5),
                ),
                (
                    "platform_rate",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "merchant_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.9,
                        help_text="Share of goods subtotal kept by merchant.",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("delivery", "Delivery"),
                            ("merchant_order", "Merchant Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ride_id", models.IntegerField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "promo_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("bankily", "Bankily"),
                            ("masrvi", "Masravi"),
                            ("seddad", "Seddad"),
                            ("promo_credit", "Promo / Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_timing",
                    models.CharField(
                        choices=[
                            ("before_delivery", "Before Delivery"),
                            ("after_delivery", "After Delivery"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        default="after_delivery",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tokenized payment reference only — never store raw card data.",
                        max_length=255,
                    ),
                ),
                (
                    "app_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "courier_earning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "merchant_earning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="MRU", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier_payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_records",
                        to="deliveries.delivery",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_records",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "merchant_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_records",
                        to="merchants.merchantorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("top_up", "Top Up"),
                    ("ride_payment", "Ride Payment"),
                    ("delivery_payment", "Delivery Payment"),
                    ("merchant_payment", "Merchant Order Payment"),
                    ("courier_earning", "Courier Earning"),
                    ("merchant_earning", "Merchant Earning"),
                    ("payout", "Payout"),
                    ("refund", "Refund"),
                    ("referral", "Referral Reward"),
                    ("bonus", "Bonus"),
                    ("adjustment", "Admin Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cancelled_order", "Cancelled Order"),
                            ("failed_delivery", "Failed Delivery"),
                            ("merchant_rejected", "Merchant Rejected Order"),
                            ("customer_complaint", "Customer Complaint"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                ("fraud_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="payments.paymentrecord",
                    ),
                ),
                (
                    "wallet_refund_tx",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to="payments.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="wallet_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_records",
                to="payments.wallettransaction",
            ),
        ),
        migrations.CreateModel(
            name="MerchantWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentrecord",
            index=models.Index(
                fields=["status", "-created_at"], name="payment_record_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrecord",
            index=models.Index(
                fields=["source", "-created_at"], name="payment_record_source_idx"
            ),
        ),
    ]
