# Generated by Django 4.2.7 on 2026-05-19 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField(default=0)),
                ("pickup_lng", models.FloatField(default=0)),
                ("destination_lat", models.FloatField(default=0)),
                ("destination_lng", models.FloatField(default=0)),
                (
                    "ride_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("XL", "XL"),
                            ("Comfort", "Comfort"),
                            ("Share", "Share"),
                        ],
                        default="Regular",
                        max_length=20,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "app_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_earning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("driver_arriving", "Driver Arriving"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
