# Generated by Django 4.2.7 on 2026-05-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="review",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ride",
            name="destination_lat",
            field=models.FloatField(default=18.0896),
        ),
        migrations.AlterField(
            model_name="ride",
            name="destination_lng",
            field=models.FloatField(default=-15.9754),
        ),
        migrations.AlterField(
            model_name="ride",
            name="distance_km",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lat",
            field=models.FloatField(default=18.0735),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lng",
            field=models.FloatField(default=-15.9582),
        ),
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_rides",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
