# Generated by Django 4.2.7 on 2026-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_ride_rating_ride_review_alter_ride_destination_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="driver_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="driver_review",
            field=models.TextField(blank=True, default=""),
        ),
    ]
