# Generated by Codex on 2026-05-26

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    Ride = apps.get_model("rides", "Ride")
    for ride in Ride.objects.filter(status="completed", completed_at__isnull=True):
        ride.completed_at = ride.created_at
        ride.save(update_fields=["completed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_ride_driver_rating_ride_driver_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
    ]
