# Generated by Django 4.2.7 on 2026-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_add_scheduled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="Referral code applied by the rider during ride request.",
                max_length=20,
                null=True,
            ),
        ),
    ]
