# Generated by Django 4.2.7 on 2026-05-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0008_add_referral_code_to_ride"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_order",
                    models.IntegerField(
                        help_text="Order of this stop in the ride sequence (1-based)."
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Display name of the stop location.", max_length=255
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the driver arrived at this stop.",
                        null=True,
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the driver departed from this stop.",
                        null=True,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["stop_order"],
                "indexes": [
                    models.Index(
                        fields=["ride", "stop_order"], name="ridestop_ride_order_idx"
                    )
                ],
                "unique_together": {("ride", "stop_order")},
            },
        ),
    ]
