# Generated by Django 6.0.5 on 2026-06-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0009_add_ridestop_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="economy_fare",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The equivalent Economy fare for savings calculation.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="seats",
            field=models.IntegerField(
                default=1, help_text="Number of seats booked (1 or 2 for Share rides)."
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="share_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waiting_match", "Waiting for Match"),
                    ("matched", "Matched"),
                    ("waiting_pickup", "Waiting for Pickup"),
                    ("picked_up", "Picked Up"),
                    ("dropped_off", "Dropped Off"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                help_text="Share-specific passenger status within a session.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ShareRideSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matching", "Matching"),
                            ("driver_assigned", "Driver Assigned"),
                            ("driver_arriving", "Driver Arriving"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="matching",
                        max_length=30,
                    ),
                ),
                (
                    "total_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
                ),
                ("route_similarity_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_sessions_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="share_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides",
                to="rides.shareridesession",
            ),
        ),
        migrations.CreateModel(
            name="ShareSessionStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("dropoff", "Drop-off")],
                        max_length=10,
                    ),
                ),
                ("stop_order", models.IntegerField()),
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("eta_minutes", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_stops",
                        to="rides.ride",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="rides.shareridesession",
                    ),
                ),
            ],
            options={
                "ordering": ["stop_order"],
            },
        ),
        migrations.AddIndex(
            model_name="shareridesession",
            index=models.Index(fields=["status"], name="share_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="shareridesession",
            index=models.Index(
                fields=["driver", "status"], name="share_session_driver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareridesession",
            index=models.Index(
                fields=["-created_at"], name="share_session_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharesessionstop",
            index=models.Index(
                fields=["session", "stop_order"], name="share_stop_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sharesessionstop",
            unique_together={("session", "stop_order")},
        ),
    ]
