# Generated by Django 4.2.7 on 2026-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0013_merge_city_and_ride_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="cancellation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fee charged to the cancelling party.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason provided for the cancellation.",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who cancelled: rider, driver, admin, or system.",
                max_length=20,
            ),
        ),
    ]
