from decimal import Decimal

import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient

from referrals.models import RiderReferralCode, RiderReferral, RideCredit

User = get_user_model()

CODE_URL = "/referrals/rider/code/"
SHARE_URL = "/referrals/rider/share/"
VALIDATE_URL = "/referrals/rider/validate/"


def _clear_auto_code(user):
    """Remove the referral code auto-generated by the post_save signal."""
    RiderReferralCode.objects.filter(rider=user).delete()


@pytest.fixture
def rider_user(db):
    """Create a regular rider user."""
    return User.objects.create_user(
        email="rider@yala-test.com",
        password="riderpass123",
        first_name="Test",
        last_name="Rider",
    )


@pytest.fixture
def authenticated_client(rider_user):
    """Return an authenticated API client for a rider."""
    client = APIClient()
    client.force_authenticate(user=rider_user)
    return client


@pytest.fixture(autouse=True)
def use_referrals_urls(settings):
    """Override ROOT_URLCONF to avoid importing firebase_admin."""
    settings.ROOT_URLCONF = "referrals.tests.test_urls"


@pytest.mark.django_db
class TestRiderReferralCodeEndpoint:
    """Tests for GET /referrals/rider/code/."""

    def test_returns_referral_code_and_stats(
        self, authenticated_client, rider_user
    ):
        """Should return referral code, successful_referrals, and total_credits_earned."""
        response = authenticated_client.get(CODE_URL)
        assert response.status_code == 200
        data = response.json()
        assert "code" in data
        assert len(data["code"]) == 8
        assert data["code"].isalnum()
        assert data["successful_referrals"] == 0
        assert Decimal(data["total_credits_earned"]) == Decimal("0.00")

    def test_returns_existing_code_if_present(
        self, authenticated_client, rider_user
    ):
        """Should return the existing code if one is already assigned."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="ABCD1234")
        response = authenticated_client.get(CODE_URL)
        assert response.status_code == 200
        data = response.json()
        assert data["code"] == "ABCD1234"

    def test_returns_401_for_unauthenticated_request(self):
        """Should return 401 for unauthenticated requests."""
        client = APIClient()
        response = client.get(CODE_URL)
        assert response.status_code == 401

    def test_returns_correct_successful_referrals_count(
        self, authenticated_client, rider_user
    ):
        """Should count only completed referrals as successful."""
        _clear_auto_code(rider_user)
        referral_code = RiderReferralCode.objects.create(
            rider=rider_user, code="TEST1234"
        )
        # Create a completed referral
        referee1 = User.objects.create_user(
            email="referee1@yala-test.com",
            password="pass123",
            first_name="Ref",
            last_name="One",
        )
        RiderReferral.objects.create(
            referral_code=referral_code,
            referee=referee1,
            status="completed",
        )
        # Create a pending referral (should not count)
        referee2 = User.objects.create_user(
            email="referee2@yala-test.com",
            password="pass123",
            first_name="Ref",
            last_name="Two",
        )
        RiderReferral.objects.create(
            referral_code=referral_code,
            referee=referee2,
            status="pending",
        )

        response = authenticated_client.get(CODE_URL)
        assert response.status_code == 200
        data = response.json()
        assert data["successful_referrals"] == 1


@pytest.mark.django_db
class TestRiderReferralShareEndpoint:
    """Tests for GET /referrals/rider/share/."""

    def test_returns_code_and_message(self, authenticated_client, rider_user):
        """Should return code and shareable message."""
        response = authenticated_client.get(SHARE_URL)
        assert response.status_code == 200
        data = response.json()
        assert "code" in data
        assert "message" in data
        assert len(data["code"]) == 8
        assert data["code"] in data["message"]

    def test_message_contains_signup_link(
        self, authenticated_client, rider_user
    ):
        """Should include a signup link in the message."""
        response = authenticated_client.get(SHARE_URL)
        data = response.json()
        assert "https://yala.app/signup" in data["message"]

    def test_returns_401_for_unauthenticated_request(self):
        """Should return 401 for unauthenticated requests."""
        client = APIClient()
        response = client.get(SHARE_URL)
        assert response.status_code == 401

    def test_uses_existing_code(self, authenticated_client, rider_user):
        """Should use the existing referral code if one is already assigned."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="SHARE123")
        response = authenticated_client.get(SHARE_URL)
        assert response.status_code == 200
        data = response.json()
        assert data["code"] == "SHARE123"


@pytest.mark.django_db
class TestRiderReferralValidateEndpoint:
    """Tests for POST /referrals/rider/validate/."""

    def test_valid_code_returns_200(self, rider_user):
        """Should return is_valid=True and the code for a valid referral code."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="GOOD1234")
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "GOOD1234"},
            format="json",
        )
        assert response.status_code == 200
        data = response.json()
        assert data["is_valid"] is True
        assert data["code"] == "GOOD1234"

    def test_valid_code_case_insensitive(self, rider_user):
        """Should accept code in any case variation."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="ABCD5678")
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "abcd5678"},
            format="json",
        )
        assert response.status_code == 200
        data = response.json()
        assert data["is_valid"] is True

    def test_invalid_format_returns_400(self):
        """Should return 400 with error when code format is invalid."""
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "SHORT"},
            format="json",
        )
        assert response.status_code == 400
        data = response.json()
        assert data["is_valid"] is False
        assert data["error_code"] == "invalid_format"

    def test_code_not_found_returns_404(self):
        """Should return 404 when code doesn't exist."""
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "NOEX1234"},
            format="json",
        )
        assert response.status_code == 404
        data = response.json()
        assert data["is_valid"] is False
        assert data["error_code"] == "code_not_found"

    def test_inactive_referrer_returns_422(self, rider_user):
        """Should return 422 when referrer's account is inactive."""
        rider_user.is_active = False
        rider_user.save()
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="INAC1234")
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "INAC1234"},
            format="json",
        )
        assert response.status_code == 422
        data = response.json()
        assert data["is_valid"] is False
        assert data["error_code"] == "referrer_inactive"

    def test_self_referral_returns_422_when_authenticated(self, rider_user):
        """Should return 422 when authenticated user tries their own code."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="SELF1234")
        client = APIClient()
        client.force_authenticate(user=rider_user)
        response = client.post(
            VALIDATE_URL,
            {"code": "SELF1234"},
            format="json",
        )
        assert response.status_code == 422
        data = response.json()
        assert data["is_valid"] is False
        assert data["error_code"] == "self_referral"

    def test_self_referral_skipped_when_unauthenticated(self, rider_user):
        """Should skip self-referral check for unauthenticated users and return valid."""
        _clear_auto_code(rider_user)
        RiderReferralCode.objects.create(rider=rider_user, code="SKIP1234")
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {"code": "SKIP1234"},
            format="json",
        )
        assert response.status_code == 200
        data = response.json()
        assert data["is_valid"] is True

    def test_missing_code_field_returns_400(self):
        """Should return 400 when code field is missing from request body."""
        client = APIClient()
        response = client.post(
            VALIDATE_URL,
            {},
            format="json",
        )
        assert response.status_code == 400
        data = response.json()
        assert data["is_valid"] is False
        assert data["error_code"] == "invalid_format"
