# Generated by Django 4.2.7 on 2026-04-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
