# Generated by Django 4.2.7 on 2026-05-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("wallet", "Wallet"),
                    ("test", "Test"),
                ],
                default="test",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RiderPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_holder_name", models.CharField(max_length=255)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                        ],
                        default="visa",
                        max_length=20,
                    ),
                ),
                ("card_last4", models.CharField(max_length=4)),
                ("expiry_month", models.CharField(max_length=2)),
                ("expiry_year", models.CharField(max_length=4)),
                ("is_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
