# Generated by Django 4.2.7 on 2026-05-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_method_riderpaymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderpaymentmethod",
            name="account_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="riderpaymentmethod",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="riderpaymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masrvi"),
                    ("seddad", "Seddad"),
                    ("cash", "Cash"),
                ],
                default="card",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="riderpaymentmethod",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="riderpaymentmethod",
            name="wallet_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masrvi"),
                    ("seddad", "Seddad"),
                    ("test", "Test"),
                ],
                default="test",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="card_holder_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="card_last4",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("amex", "American Express"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="expiry_month",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="riderpaymentmethod",
            name="expiry_year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
