# Generated by Django 4.2.7 on 2026-05-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_riderpaymentmethod_account_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_verification", "Pending Verification"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
