# Generated by Django 4.2.7 on 2026-05-25 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0005_payment_tip_amount_payment_tip_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverPayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("card", "Card"),
                            ("bankily", "Bankily"),
                            ("masrvi", "Masrvi"),
                            ("seddad", "Seddad"),
                        ],
                        default="bank_account",
                        max_length=30,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("card_last4", models.CharField(blank=True, default="", max_length=4)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("wallet_id", models.CharField(blank=True, default="", max_length=100)),
                ("is_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_payout_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MRU", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payout_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.driverpayoutmethod",
                    ),
                ),
            ],
        ),
    ]
