# Generated by Django 4.2.7 on 2026-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Promo code discount amount applied to this payment.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
