# Generated by Django 4.2.7 on 2026-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_walletaccount_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("bankily", "Bankily"),
                    ("masrvi", "Masravi"),
                    ("seddad", "Seddad"),
                    ("wallet", "Yala Wallet"),
                    ("test", "Test"),
                ],
                default="test",
                max_length=30,
            ),
        ),
    ]
