# Generated by Django 6.0.5 on 2026-07-23 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_rc3_stabilization_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="finance_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="finance_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_approved_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="requires_dual_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("awaiting_ceo", "Awaiting CEO Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
